### ISSUE TITLE
Something seems to went wrong converting ``u`` to ``userdata``.

### ISSUE THREAD

**Issue by philippeowagner** [Pushwoosh/pushwoosh-phonegap-plugin#10]
https://github.com/shaders/pushwoosh-phonegap-3.0-plugin/blob/a522eefd06c16d523d17fed78ef7e7da3d47e8b5/src/ios/PushRuntime.m#L68

I can't access to `var userData = notification.userdata;` but `notification.u` hold the data.

**Comment by shaders** [comment]
added in this commit: https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/commit/7acb1b8b287f2b0b08f59ebcd1077e063ded2b67
