### ISSUE TITLE
I don't understand ttl and priority, please help me

### ISSUE THREAD

**Issue by xale76** [Pushwoosh/pushwoosh-phonegap-plugin#139]
hello, Ive used ttl and priority (ttl=3600, priority=1). Im logged in my app, so if I send test push I receive it.
Well, now I turn off the phone internet connection. I send a test push. I wait 5 mins and I turn on back my connection. I don't receive the push. How it comes? What's wrong?

And what's android priority? -2 has more priority than 2 or viceversa?
thank you

**Comment by shaders** [comment]
1. checking

2. http://developer.android.com/design/patterns/notifications.html 
look for ("Correctly set and manage notification priority")

**Comment by xale76** [comment]
thx I understand point 2, but -2 is very urgent?

**Comment by shaders** [comment]
-2 is "low", 2 is "max"

**Comment by xale76** [comment]
I go on with this problem. I didn't fix it. If the app is closed by OS (Android) and I send a push, when I start the app, the push is not received. Have to put some code inside my app to handle this special condition?

**Comment by shaders** [comment]
You have to tap on the notification itself so the operating system will pass the notification to the app.

**Comment by xale76** [comment]
hello, the notification is not received at all. So I cannot tap on anything
