### ISSUE TITLE
Phonegap Build copys binaries for release iOS builds resulting in Invalid Bundle Structure.

### ISSUE THREAD

**Issue by didius111** [Pushwoosh/pushwoosh-phonegap-plugin#142]
When doing a release build in phonegap, the default configuration of the ios pushwoosh plugin copies raw binary files into the bundle resulting in apple not accepting the app for submission due to the fact the bundle contains other binary code. 

The error generated is

"Invalid Bundle Structure the binary file .... is not permitted, your app cannot contain standalone executables or libraries"

This error was resolved when removing the two pushwoosh binraries from the plugins folder and rebuiling the iOs app. This also resulted in a reduction of the application size by 10megs. 

Suggested solutions wold either be remove the binaries from the master repo or configure the build steps so that the raw binaries do not get copied over in the build process.

**Comment by shaders** [comment]
What are these two files you are referring to? What are their names and the location?

**Comment by didius111** [comment]
https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/blob/master/src/ios/Pushwoosh.framework/Pushwoosh

and

https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/blob/master/src/ios/Pushwoosh.framework/Versions/A/Pushwoosh

They appear to be copied over in the build process into the bundle - which is wigging apple out since  the bundle ends up containing a binary that isn't the app itself.

**Comment by shaders** [comment]
That's weird. The first one is actually symlink file to the second one. You can see it's value on github: "Versions/Current/Pushwoosh".

The second one is the library code itself. You can't link the project without it.

As you can see from the config.xml these files are not copied anywhere:
https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/blob/master/plugin.xml

        <header-file src="src/ios/Pushwoosh.framework/Versions/A/Headers/PushNotificationManager.h" target-dir="ios"/>
        <source-file src="src/ios/Pushwoosh.framework/Versions/A/Pushwoosh" framework="true"/>

Maybe Phonegap broke something and started to copy these files. What is your Phonegap (Cordova) version?

**Comment by didius111** [comment]
Yeah - well it needs the file to link - but it looks like for whatever reason phonegap build is also just copying the entire plugins folder into the bundle. It seems to be related to how the xcode project gets configured. 

We are on phonegap 5.3.5

**Comment by shaders** [comment]
Do you use Phonegap (Cordova CLI) or Phonegap build?

**Comment by didius111** [comment]
It was a phonegap build. 

When we built it native with xcode everything worked as expected and the build was accepted.

**Comment by shaders** [comment]
That's strange I couldn't reproduce this with the sample app here:
https://github.com/Pushwoosh/phonegap-3-sample-app

If your app repository public so I can try to build it with PGB?

**Comment by rafaelfe** [comment]
Fix for this problem: just remove any plugin folders inside cordova's plugin folder. 
[your project]/plugins/     <-- remove all folders inside this one.
