### ISSUE TITLE
Use various PhoneGap apps Pushwoosh, you can not install together.

### ISSUE THREAD

**Issue by RonnySchleicher** [Pushwoosh/pushwoosh-phonegap-plugin#149]
##### Step to Reproduce:

* Create a new Phonegap Application (in this example on the PC):

* Identifier and Name **de.myapp.myapp MYAPP**

```batch
cd c:\

call cordova create PhoneGap_android de.myapp.myapp MYAPP

cd PhoneGap_android

call cordova platform add android

call cordova plugin add https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin.git

call cordova plugin add cordova-plugin-whitelist@1.0
call cordova plugin add cordova-plugin-network-information
call cordova plugin add cordova-plugin-device
call cordova plugin add cordova-plugin-splashscreen
call cordova plugin add cordova-plugin-console
```

* Open the project in the Android Studio

* Now add the needed dependency in the build.gradle file **compile "com.google.android.gms:play-services-gcm:+"**

```gradle
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile project(path: "CordovaLib", configuration: "debug")
    releaseCompile project(path: "CordovaLib", configuration: "release")
    compile "com.google.android.gms:play-services-gcm:+"
    // SUB-PROJECT DEPENDENCIES END
}

```

* Try to install and run the MYAPP on a real Android device

* **Also is fine!** The App can be installed and lanched too.

* Close the App and close the Android Studio too

* Create a second new Phonegap App

* Identifier and Name are completely different to the first APP **de.myapp2.myapp2 MYAPP2**

```batch
cd c:\

rd .\PhoneGap_android2 /S /Q

call cordova create PhoneGap_android2 de.myapp2.myapp2 MYAPP2

cd PhoneGap_android2

call cordova platform add android

call cordova plugin add https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin.git

call cordova plugin add cordova-plugin-whitelist@1.0
call cordova plugin add cordova-plugin-network-information
call cordova plugin add cordova-plugin-device
call cordova plugin add cordova-plugin-splashscreen
call cordova plugin add cordova-plugin-console
```
* Open the second project in the Android Studio

Now add also the dependency in build.gradle file **compile "com.google.android.gms:play-services-gcm:+"**

```gradle
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile project(path: "CordovaLib", configuration: "debug")
    releaseCompile project(path: "CordovaLib", configuration: "release")
    compile "com.google.android.gms:play-services-gcm:+"
    // SUB-PROJECT DEPENDENCIES END
}

```

* Try to install and run the ***MYAPP2*** on the same real  Android device (MYAPP is still installed)

* Follow error message appear

![image](https://cloud.githubusercontent.com/assets/1914203/12246839/15b99d7e-b8b1-11e5-919b-99feea099367.png)

Then trying uninstalling proposes course fail. Because App does not exist.

* **You can never install more then one PhoneGap App with the PushWoosh-Plugin and the required dependency (compile "com.google.android.gms:play-services-gcm:+") on the same device**

* **This also happens with released Apps (sent via email as an APK MYAPP and MyApp2)**

* **And it happens even if the apps are installed from the** :exclamation: Play Store :exclamation: ** Mostly then comes the error -505**

* Without dependencies it would work. But then I can not use PUSHWOOSH. Because PUSHWOOSH the dependencies needs.

**Comment by RonnySchleicher** [comment]
##### Enviorenment
* Android Studio 1.5.1
* PhoneGap 5.4.1 (but also happend with 5.3.3)

```Javascript
    "cordova-plugin-whitelist": "1.2.0",
    "com.pushwoosh.plugins.pushwoosh": "3.6.16",
    "cordova-plugin-device-motion": "1.2.0",
    "cordova-plugin-file": "3.0.0",
    "cordova-plugin-media-capture": "1.1.0",
    "cordova-plugin-device-orientation": "1.0.2",
    "cordova-plugin-network-information": "1.1.0",
    "cordova-plugin-contacts": "1.1.0",
    "cordova-plugin-device": "1.1.0",
    "cordova-plugin-battery-status": "1.1.1",
    "cordova-plugin-file-transfer": "1.4.0",
    "cordova-plugin-geolocation": "1.0.1",
    "cordova-plugin-globalization": "1.0.2",
    "cordova-plugin-inappbrowser": "1.1.1",
    "cordova-plugin-media": "1.0.1",
    "cordova-plugin-dialogs": "1.2.0",
    "cordova-plugin-vibration": "2.0.0",
    "cordova-plugin-splashscreen": "3.0.0",
    "cordova-plugin-console": "1.0.2",
    "cordova-plugin-statusbar": "2.0.0"
```

**Comment by shaders** [comment]
Hi,

VERY IMPORTANT: There is a bug in cordova generated projects for Android https://code.google.com/p/analytics-issues/issues/detail?id=784. As a result you will be unable to install more than one application with pushwoosh on same device.

As a workaround you can add in build.gradle:
android {
defaultConfig.applicationId = "your.package.id"
}

**Comment by RonnySchleicher** [comment]
It works great. Thank you for your help.

**Comment by luizwagner** [comment]
We are having the same problem, but used the Intel XDK, has planned some solution for this platform?

Help us, the application is in production and can not deliver to my clients.

Thank you!

**Comment by shaders** [comment]
Intel XDK uses Cordova under the hood. I suppose the same change would fix Intel XDK as well.

**Comment by almemar87** [comment]
what if Intel XDK doesn't support gradle yet. Is there any way around to solve this issue?
