### ISSUE TITLE
Android setTags() mystery

### ISSUE THREAD

**Issue by christoph-schindler** [Pushwoosh/pushwoosh-phonegap-plugin#150]
Hi, I have a serious problem with the setTags function. At first: everything works fine for iOS and it's alright for Android with a new installed (not updated) app, too. The Problem accrues only at Android, when you update the existing app. In this special case, the setTags function seems to fail: When you send a push with filter for this tag, pushwoosh does not do it anymore. The setTags function itself responses a success and getTags show me the right tag values. But pushwoosh does not send to this device anymore. How can that happen?

The big mystery: If you deinstall the app and make clean new install again, everything works as expected. BUT if you update the same app with the same apk, the problem occurs again!? This means: all our android users that update our app via playstore can not use the pushwoosh service any more. We are at a loss with this behaviour.

Because of phonegap issues, we need to use this plugin (https://build.phonegap.com/plugins/1297) also it's deprecated. This version (https://www.npmjs.com/package/pushwoosh-pgb-plugin) should be the newest. So my question: can you update this plugin too... in the hope that it works then.

**Comment by shaders** [comment]
Could you please paste logs before and after you update the app?
Thanks!

**Comment by shaders** [comment]
Ok looks like the thread stalled. Closing the issue.
