### ISSUE TITLE
"Alert: Attempt to invoke virtual method.."

### ISSUE THREAD

**Issue by verdio** [Pushwoosh/pushwoosh-phonegap-plugin#151]
Hi,

I am using Phone Gap Build with Pushwoosh plugin: <plugin name="com.pushwoosh.plugins.pushwoosh" spec="3.4.2" source="pgb"/>

The messages are being sent correctly, and "actions" are working, but when I launch the my app I am getting this "Alert" dialogue and do not know how to correct the situation.

Here is the full alert (it appears on launch of the app only):

"Alert Attempt to invoke virtual method 'void com.arellomobile.android.push.PushManager.registerForPushNotifications()' on a null object reference"

Thoughts?

Mark

**Comment by shaders** [comment]
Please specify which plugin version do you use?
It looks like the plugin is outdated, the package name has been changed in the latest SDK.

**Comment by verdio** [comment]
<plugin name="com.pushwoosh.plugins.pushwoosh" source="pgb" spec="3.4.2" />

was what I used.

**Comment by DimanAM** [comment]
https://build.phonegap.com/plugins/1297 is deprecated.

The correct way of including plugin is:

&lt;gap:plugin name="pushwoosh-pgb-plugin" source="npm" /&gt;
&lt;preference name="android-build-tool" value="gradle" /&gt;

**Comment by verdio** [comment]
Do I also need some javascript somewhere to initialize the plugin, etc ???

**Comment by DimanAM** [comment]
Just follow this guide http://docs.pushwoosh.com/docs/phonegap-build
There is also a sample https://github.com/Pushwoosh/phonegap-build-sample-app
