### ISSUE TITLE
Register Not Working After Second Time Registering in Phonegap in iOS

### ISSUE THREAD

**Issue by shmdhussain** [Pushwoosh/pushwoosh-phonegap-plugin#152]
I am Toggling the register and unregister to receive the notification in Phonegap App(using pushwoosh plugin 3.4.2). The states are

 1. Initially The app state is in unregistered, Now I send Push Woosh Notification, Device in consideration is not receiving and all other devices are receiving(which are in registered state) ---- Result::Working Correctly
 2. Now I registered in the device and got success callback running for register and now I send Push Woosh Notification, Device in consideration is receiving ---- Result::Working Correctly
 3. Now I un registered in the device and got success callback running for unregister and now I send Push Woosh Notification, Device in consideration is not receiving ---- Result::Working Correctly
 4. Now I again registered in the device and got success callback running for register and now I send Push Woosh Notification, Device in consideration is not receiving ---- Result:: Not Working Correctly

Could You help me why I got this behaviour even I Got all success callbacks when i register and unregister?. Thanks in advance for any help.

**Comment by shaders** [comment]
Hi,

This has been fixed. Thanks!

**Comment by shmdhussain** [comment]
Thank You!!
