### ISSUE TITLE
Android 5.0.2

### ISSUE THREAD

**Issue by xale76** [Pushwoosh/pushwoosh-phonegap-plugin#155]
notifications don't arrive when App is in foreground on Android 5.0.2 (on prev version it works fine). Please help me

pushwoosh-plugin version 3.5.9

**Comment by DimanAM** [comment]
Foreground pushes are handled automatically. Alert blinks at the top of the screen and notification callback is automatically called (if it does not it's obviously a bug). If you want different behaviour you can  set ```PW_NO_BROADCAST_PUSH``` metadata with value ```true``` in AndroidManifest.xml.

**Comment by xale76** [comment]
Dont understand. With the same app in other android os even when app is in
foreground a icon on top of phone header appears when push arrives. So my
question was: is there an option that I can set to force the icon to
appear?
Il 25/Gen/2016 06:40, "DimanAM" <notifications@github.com> ha scritto:

**Comment by shaders** [comment]
An icon on top of the phone is managed by Android OS. What specific Android OS version you refer to the "prev version"?

Do you experience something similar?
http://docs.pushwoosh.com/docs/android-faq#how-to-set-a-notification-icon-in-android-lollipop
