### ISSUE TITLE
Geolocation not stopping

### ISSUE THREAD

**Issue by robobobo** [Pushwoosh/pushwoosh-phonegap-plugin#158]
Have noticed in V 4.2.0 09beb45bbe8334844733f126a5aa0d99062882cf that the geolocation feature never disables on Android

```javascript
pushNotification.stopLocationTracking();
``` 

Doesn't seem to be doing anything, the GPS stays on draining the battery until the application is force closed. This appears to be happening on Android 5.1.1.

In the last previous version I had tested 3.6.16 6df63af7da312a6cfdf25bb49ce45b7ea04cde42 the `stopLocationTracking` function disabled the GPS tracking

**Comment by wfhm** [comment]
Hi,

We couldn't reproduce this behaviour on our sample. Could you please send an .apk reproducer to help@pushwoosh.com so we could try it on our side? 

Also it would be nice if you could specify your device's model.

**Comment by robobobo** [comment]
I was testing with a Samsung Galaxy S6 Edge. I will get an apk together and send on when I get a chance
