### ISSUE TITLE
Plugin adds Geolocation permission even though no Geolocation features are being used

### ISSUE THREAD

**Issue by VictorBjelkholm** [Pushwoosh/pushwoosh-phonegap-plugin#159]
Hey!

Recently after updating the plugin, the application asks for permission to use the Geolocation features of the phone, even though we use no geolocation features from Pushwoosh or at all.

How can we work around this? The only way I can see is if we fork this repository and maintain our fork without any geolocation features but I would like to avoid this.

Any advice on this?

I left a note here https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/commit/e194bd2dc0537c4b2a5e78b4ac9b92b0844319c5#commitcomment-16143334 and also wrote support but have yet to receive any response so opening this issue is my last try to contact you.

**Comment by DimanAM** [comment]
As a workaround you can remove these permissions from platforms/android/AndroidManifest.xml:
<pre>
&lt;uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" /&gt;
&lt;uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /&gt;
</pre>
And build project using Android Studio.

**Comment by VictorBjelkholm** [comment]
@DimanAM Thanks for the proposed workaround, it's what we're currently doing. But we'd like to have a reproducible build and we're trying to not have the platforms/ directory in SCM.

But as a workaround it's valid, thanks.

**Comment by arzanardi** [comment]
@VictorBjelkholm I'm with you! 
We need this too.
