### ISSUE TITLE
SERVICE_NOT_AVAILABLE when I register an Android Device

### ISSUE THREAD

**Issue by sandroweb** [Pushwoosh/pushwoosh-phonegap-plugin#160]
This error occure in some Android devices, but running correctly in iOS.

**Comment by wfhm** [comment]
Hi,

Could you please provide a bit more details on your issue? Any logs or screenshots descrbing the issue will be highly appreciated.

**Comment by DimanAM** [comment]
This [error](https://developers.google.com/android/reference/com/google/android/gms/gcm/GoogleCloudMessaging#ERROR_SERVICE_NOT_AVAILABLE
) means your device could not connect to GCM.
If this error appears constantly, make sure you have internet connection and GCM ports are accessible (devices access the GCM servers on ports 5228-5230)
