### ISSUE TITLE
Plugin version 4.2.0 not working anymore on iOS 9

### ISSUE THREAD

**Issue by shatting** [Pushwoosh/pushwoosh-phonegap-plugin#161]
I have updated from 4.0.0 and now notifications only work very sporadically if at all. After a push that worked, the Push API server responds with my devices Id in "unknownDevices". A downgrade to 4.0.0 fixed this immediately. Im guessing it might have to do with the framework update at https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/commit/e194bd2dc0537c4b2a5e78b4ac9b92b0844319c5.

**Comment by shatting** [comment]
never mind, i reverted all code and it now works again.

**Comment by shaders** [comment]
What was the problem?
