### ISSUE TITLE
Fix issue cordova name and id

### ISSUE THREAD

**Issue by gabfiocchi** [Pushwoosh/pushwoosh-phonegap-plugin#164]
Fix bug with install plugin on cordova or ionic. Cordova id is different to name of this, and this issue make some bugs on the project.

You need replace 'com.pushwoosh.plugins.pushwoosh' to 'pushwoosh-cordova-plugin' in all files.

`Error executing "cordova plugin add com.pushwoosh.plugins.pushwoosh":
Fetching plugin "com.pushwoosh.plugins.pushwoosh" via npm
Error: Failed to fetch plugin com.pushwoosh.plugins.pushwoosh via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.pushwoosh.plugins.pushwoosh`

**Comment by fgilio** [comment]
+1

**Comment by shaders** [comment]
You adding the plugin in the wrong way as: 

        cordova plugin add com.pushwoosh.plugins.pushwoosh

Take a look on the guide:
http://docs.pushwoosh.com/docs/cordova-phonegap

The correct way of adding the plugin is:
Cordova: 

        cordova plugin add pushwoosh-cordova-plugin

Ionic:

        ionic plugin add pushwoosh-cordova-plugin

**Comment by gabfiocchi** [comment]
@shaders:
No, when I run Cordova o Ionic add `pushwoosh-cordova-plugin`, add the right plugin, but if you try restore project or list the cordova plugins `cordova plugin list` or `ionic plugin list`, happened bug because pushwoosh on the package.json has the old id, and 
**npm, try install the plugin on the cordova id:**

`com.pushwoosh.plugins.pushwoosh`, not `pushwoosh-cordova-plugin`.

It's a problem with the cordova id.

**Comment by shaders** [comment]
I've merged your request. I need to increase version and republish this to npm.

**Comment by gabfiocchi** [comment]
Thanks!

**Comment by shaders** [comment]
4.2.1 published
