### ISSUE TITLE
pushwoosh and admob doesn't work together

### ISSUE THREAD

**Issue by almemar87** [Pushwoosh/pushwoosh-phonegap-plugin#167]
Hello guys, 
I've been trying for the past 4 days to bring together pushwoosh Intel XDK and Admob plugins together but there's an issue with that. It doesn't build and showing an error of fails or can't install. However, I tried each one separately and it work just fine. are you aware of this issue? Any suggestion to change anything? 
Many thanks to all of you in advance

**Comment by DimanAM** [comment]
What Admob plugin do you use?
Which platform are you building?
What is the error?

**Comment by almemar87** [comment]
Thanks for your reply,

Admob
admob plugin: cordova-plugin-admob
which depends on two other plugins: 1) com.google.playservices
and 2) com.google.admobsdk

Platform
Android

Error 

The build failed. An error occurred while building the application. Verify your build assets are correct and try again.
Build Log:
Building a Cordova 5.1.1 application.
Building with cordova-android 4.1.1.
The application name is "trynew01"
The package name is "com.trynew.demo"
Plugin "cordova-plugin-statusbar" (2.0.0) installed.
Plugin "cordova-plugin-device" (1.1.0) installed.
Plugin "cordova-plugin-splashscreen" (2.1.0) installed.
Plugin "cordova.plugin.admob" (5.4.2) installed.
Error: Plugin Pushwoosh failed to install.
Plugin "cordova-plugin-whitelist" (1.2.1) installed.
Error: Plugin Google Play Services for Android failed to install.
Error: Plugin AdMob SDK for Android, iOS and WP8 failed to install.
Error: Plugin AdMob failed to install.

**Comment by almemar87** [comment]
I used this pushwoosh sample work and it works just fine
https://github.com/Pushwoosh/phonegap-build-sample-app

**Comment by almemar87** [comment]
I used this pushwoosh sample work and it works just fine
https://github.com/Pushwoosh/pushwoosh-phonegap-cordova-sample/tree/master/Intel-XDK

**Comment by DimanAM** [comment]
It's likely a problem with conflicting google play services. Unfortunately we cannot use gradle reference like in master branch for Intel XDK (see https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/pull/156)
As a workaround you can actually use master branch (pushwooosh-cordova-plugin or pushwoosh-pgb-plugin) with versions less than 4.2.0 . But you will face this problem https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/149.

**Comment by almemar87** [comment]
Many thanks DiamnAM, I'll try to follow. hopefully it'll be resolved

**Comment by almemar87** [comment]
Problem solved
pushwoosh version 3.6.2 works just fine with cordova-plugin-admob in Intel-xdk for Android platform

**Comment by axemclion** [comment]
Looks like this is fixed in https://issues.apache.org/jira/browse/CB-10014, https://github.com/apache/cordova-android/commit/fb9cf60c4100d5bc6f9320747611da1ca0ced289

**Comment by shaders** [comment]
@axemclion Great news! Closing the ticket.
