### ISSUE TITLE
Warning: No such file or directory

### ISSUE THREAD

**Issue by ginevive** [Pushwoosh/pushwoosh-phonegap-plugin#173]
After updated to version 5.0.0, I am getting the following warnings when building for IOS.

`while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(PWBaseTracker.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/2FRFWHA7C94TV/UIKit-2OTVYEUB2TJWZ.pcm: No such file or directory
note: Module debugging should be disabled when shipping static libraries.
while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(PWBaseTracker.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/2FRFWHA7C94TV/Foundation-164SPWHKWPMY7.pcm: No such file or directory
while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(PWBaseTracker.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/2FRFWHA7C94TV/CoreLocation-1THMVJ3OJRTG6.pcm: No such file or directory
while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(PWBaseTracker.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/2FRFWHA7C94TV/ObjectiveC-35Q3FTV4R33D2.pcm: No such file or directory
while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(PWNetworkEngine.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/2FRFWHA7C94TV/SystemConfiguration-3IKUWXIK8N53I.pcm: No such file or directory
while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(PWNetworkEngine.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/2FRFWHA7C94TV/Darwin-3R2UTED00273P.pcm: No such file or directory
while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(PWNetworkEngine.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/2FRFWHA7C94TV/CoreGraphics-1WLF4XS7UB9N.pcm: No such file or directory
while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(PWInAppEventDispatcher.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/2FRFWHA7C94TV/StoreKit-21C6T7PI8TEBV.pcm: No such file or directory
while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(PWZipArchive.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/com.apple.DeveloperTools/7.2.1-7C1002/Xcode/7.2.1-7C1002/Xcode/SharedPrecompiledHeaders/PushNotificationManager_prefix-coyrbchrziekaghescybdqbybryv/PushNotificationManager_prefix.pch.pch: No such file or directory
while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(GTMNSString+HTML.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/2FRFWHA7C94TV/CoreFoundation-391KGV3REETIC.pcm: No such file or directory
while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(PWNotificationCenter.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/2FRFWHA7C94TV/AVFoundation-23W3OEF553MUM.pcm: No such file or directory
while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(PWHtmlWebViewController.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/2FRFWHA7C94TV/QuartzCore-1EFHIRPEUZPEY.pcm: No such file or directory
while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(PWNetworkOperation.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/2FRFWHA7C94TV/ImageIO-1WLF4XS7UB9N.pcm: No such file or directory
while processing myApp/Plugins/pushwoosh-cordova-plugin/Pushwoosh(PWNetworkOperation.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/2FRFWHA7C94TV/Security-2UZCDM9YJN8K3.pcm: No such file or directory`

I tried reinstalling the plugin, plus removed and added the IOS platform again just to be on the safe side, but the warnings still occur.

**Comment by shaders** [comment]
This has been fixed in the latest update!

**Comment by ginevive** [comment]
Thank you!  Looks great now.
