### ISSUE TITLE
[Android] Remove setting applicationID as a dependency

### ISSUE THREAD

**Issue by axemclion** [Pushwoosh/pushwoosh-phonegap-plugin#176]
Pull Request #157 fixes the issue where `applicationID` is not set by the project.

Looks like this is fixed in [CB-10014](https://issues.apache.org/jira/browse/CB-10014) and a [corresponding commit](https://github.com/apache/cordova-android/commit/fb9cf60c4100d5bc6f9320747611da1ca0ced289).

We could get do away with this commit. To ensure that the plugin works with versions where this is fixed in Cordova, we could leverage Cordova's [plugin pinning](https://issues.apache.org/jira/browse/CB-10679).

This commit is causing the plugins to be unusable with [react-native-cordova-plugin](http://github.com/axemclion/react-native-cordova-plugin). The fundamental issue is that ReactNative includes plugins as libraries, while Cordova simply changes build files to make plugins a part of the main project. A library cannot have an `applicationID` and thus, this library can only be used when included in a main project as a result of computing `applicationID` in gradle. 

A library cannot really set an applicationID.

**Comment by shaders** [comment]
Pushwoosh plugin for react native will be published in a few days!
