### ISSUE TITLE
Plugin crashes Android app

### ISSUE THREAD

**Issue by sarpay** [Pushwoosh/pushwoosh-phonegap-plugin#177]
Everything was working just right until couple days back. Plugin calls like registerDevice and unregisterDevice are causing app to crash without being able to produce an exception in debug mode. (using the Visual Studio Telerik AppBuilder client). Is this a known issue? Has anyone encountered a similar problem lately? Tested on Android 6.

**Comment by Lecramed** [comment]
Yes we have the same problem! 
Our app crashes on regesterDevice. 
Do we have to update our plugin?

**Comment by shaders** [comment]
Do you have crash log from the phone console?

**Comment by named8** [comment]
Hi, we have the same problem.
in my logacat there is this message: "FATAL EXCEPTION: IntentService[GCMRegistrationService]".

**Comment by iwantwin** [comment]
We have the same problem! I do not have any recent log messages, but we downgraded to an older version of the plugin to escape from the problems.

**Comment by shaders** [comment]
@iwantwin  @Lecramed  @sarpay @named8 Could you please provide the full logs from the device?

**Comment by named8** [comment]
In attach a part of my Logcat
[logcat.txt](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/files/279786/logcat.txt)

**Comment by named8** [comment]
In attach a part of my LogCat
[logcat.txt](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/files/279791/logcat.txt)

**Comment by shaders** [comment]
05-24 17:55:58.688: E/AndroidRuntime(23600): FATAL EXCEPTION: IntentService[GCMRegistrationService]
05-24 17:55:58.688: E/AndroidRuntime(23600): Process: ****************************, PID: 23600
05-24 17:55:58.688: E/AndroidRuntime(23600): java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
05-24 17:55:58.688: E/AndroidRuntime(23600): 	at com.google.android.gms.iid.zzd.zzeC(Unknown Source)
05-24 17:55:58.688: E/AndroidRuntime(23600): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
05-24 17:55:58.688: E/AndroidRuntime(23600): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
05-24 17:55:58.688: E/AndroidRuntime(23600): 	at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
05-24 17:55:58.688: E/AndroidRuntime(23600): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
05-24 17:55:58.688: E/AndroidRuntime(23600): 	at com.pushwoosh.GCMRegistrationService.register(GCMRegistrationService.java:37)
05-24 17:55:58.688: E/AndroidRuntime(23600): 	at com.pushwoosh.GCMRegistrationService.onHandleIntent(GCMRegistrationService.java:106)
05-24 17:55:58.688: E/AndroidRuntime(23600): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
05-24 17:55:58.688: E/AndroidRuntime(23600): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-24 17:55:58.688: E/AndroidRuntime(23600): 	at android.os.Looper.loop(Looper.java:145)
05-24 17:55:58.688: E/AndroidRuntime(23600): 	at android.os.HandlerThread.run(HandlerThread.java:61)
05-24 17:55:58.688: W/ActivityManager(967):   Force finishing activity 1 ****************************/.MainActivity

Ok, it looks like google play services library you use is outdated :(

The Pushwoosh plugin references the latest library as per Cordova guides:
framework src="com.google.android.gms:play-services-gcm:+" 

If using Intel XDK - you have to upgrade to the latest version of Intel XDK.
If using any other builder - this might happen if any other plugin has outdated Google Play Services.jar file. You have to remove google-play-services.jar references/files from other plugins.
You may ALSO need to update your Android SDK, especially Google Play Services.

Closing the thread now.

**Comment by shaders** [comment]
Oh yes, you also need to update Android Support Library as per my comment above:

The plugin references the latest version of Android Support Library:
framework src="com.android.support:support-v4:+

**Comment by named8** [comment]
Yes but I have already update the Android Support Library as you can seen in the picture.
![image](https://cloud.githubusercontent.com/assets/19552174/15534993/bdfc9602-226b-11e6-9413-33a8e01bacf6.png)
I also installed Android 6.0 and 5.1

**Comment by shaders** [comment]
This is what I have:

cd platforms/android
./gradlew :dependencies

_releaseApk - ## Internal use, do not manually configure ##
+--- com.google.android.gms:play-services-gcm:8.4.0
|    +--- com.google.android.gms:play-services-base:8.4.0
|    |    \--- com.google.android.gms:play-services-basement:8.4.0
|    |         \--- com.android.support:support-v4:23.0.0 -> 23.1.0
|    |              \--- com.android.support:support-annotations:23.1.0
|    \--- com.google.android.gms:play-services-measurement:8.4.0
|         \--- com.google.android.gms:play-services-basement:8.4.0 (*)
+--- com.google.android.gms:play-services-location:8.4.0
|    +--- com.google.android.gms:play-services-base:8.4.0 (*)
|    \--- com.google.android.gms:play-services-maps:8.4.0
|         \--- com.google.android.gms:play-services-base:8.4.0 (*)
+--- com.pushwoosh:pushwoosh:4.1.2
+--- com.android.support:support-v4:23.1.0 (*)
\--- project :CordovaLib

**Comment by named8** [comment]
where can I chack this references?
I use cordova in the command.
Thanks

**Comment by DimanAM** [comment]
@named8 
Just run
```
cordova build android
cd platforms/android
./gradlew :dependencies
```

**Comment by named8** [comment]
Perhaps I didn't understand, but if I run in command: 

> cordova build android
> cd platforms/android
> ./gradlew :dependencies

return this message error:
"Error: Unknown platforms: cd, platforms/android, ./gradlew, :dependencies

**Comment by named8** [comment]
Any hint? thanks

**Comment by DimanAM** [comment]
@named8 
These 3 lines are separate commands:
```
cordova build android
cd platforms/android
./gradlew :dependencies
```

If you want to run them in one line:
```
cordova build android && cd platforms/android && ./gradlew :dependencies
```

Alternatively you can open platforms/android in Android Studio and run in Terminal:
```
./gradlew :dependencies
```

(On Windows use gradlew.bat)

**Comment by Lecramed** [comment]
I use the telerik appbuilder verified plugin
Is there a way to solve it in there?

**Comment by named8** [comment]
I wrote your code in command:
![image](https://cloud.githubusercontent.com/assets/19552174/15578393/92ae7b3c-2360-11e6-9f34-3437a037e9d3.png)

but return a error message:
![image](https://cloud.githubusercontent.com/assets/19552174/15578486/eab556e8-2360-11e6-864a-50cdd50f2082.png)

**Comment by named8** [comment]
Please anyone can help me?
This plugin it's important for my app and now if I add it my application became unusable.
Thanks

**Comment by shaders** [comment]
Let me google it for you :)
http://stackoverflow.com/questions/24216612/gradle-cannot-find-the-androidsdk-path-on-windows

**Comment by named8** [comment]
@shaders thanks for your help (and your humor) but my problem with this plugin continues to exist.
I have problem only with this plugin and only after his upgrade.
I think is not possible is only dependencies problem.

**Comment by shaders** [comment]
The problem has been identified above. You are using different incompatible versions of Android Support V4 and Google Play Services from Android SDK.

I need the results of this gradleview command.

**Comment by named8** [comment]
Ok thanks.
Also with the correct instructions I have problem in command. I don't know

**Comment by shaders** [comment]
I think this might be an issue:
https://github.com/Telerik-Verified-Plugins/Pushwoosh/issues/5

I think you need to update Telerik plugin to Pushwoosh plugin. They are using old old old fork of 3.6.16
