### ISSUE TITLE
com.pushwoosh.plugins.pushwoosh.PushNotification not found

### ISSUE THREAD

**Issue by adityasaxena** [Pushwoosh/pushwoosh-phonegap-plugin#180]
hello! We're still using version 3.6.16 in one of our apps. Recently, since about 3 days or so, I'm constantly getting this error
`com.pushwoosh.plugins.pushwoosh.PushNotification not found` when I do `var pushNotification = cordova.require('com.pushwoosh.plugins.pushwoosh.PushNotification');`

What I've confirmed:
1. The plugin installs just fine in the `plugins` directory
2. We've changed nothing in our codebase since the last 3 days

Any clues as to what could be going on would be really helpful.

**Comment by DimanAM** [comment]
If you are still using 3.6.16 try cleaning your project (remove `platforms` and `plugins` directories and install all plugins again).
If you use latest plugin (>=4.2.2) you should call:
`var pushNotification = cordova.require("pushwoosh-cordova-plugin.PushNotification");`

**Comment by adityasaxena** [comment]
@DimanAM I had tried that yesterday. But, what do you know, each new day brings new surprises. Cleaning up directories worked! thanks a ton. I'll close this.
