### ISSUE TITLE
change notification title

### ISSUE THREAD

**Issue by superainovacoes** [Pushwoosh/pushwoosh-phonegap-plugin#183]
Hi, how can we change the notification title on pushs?

example: my application name is "super app" on android/ios the notificaton title always come with "super app", there's a way to change "super app" to "wow my super app" on the createmessage payload?

thanks

https://community.pushwoosh.com/questions/3597/change-notification-title

**Comment by shaders** [comment]
Can you try "android_header" parameter?

**Comment by superainovacoes** [comment]
it works for android @shaders, does ios have an "ios_header" or any plans do implement soon?

**Comment by shaders** [comment]
iOS always shows the App Title. Unfortunately this is iOS behavior that could not be customized.

**Comment by superainovacoes** [comment]
i think it's possible since iOS 8.2 

you can see it here: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html

**Comment by shaders** [comment]
Let me check with the team.

**Comment by shaders** [comment]
This is for Apple Watch only. iPhone/iPad ignores the title property :(

**Comment by superainovacoes** [comment]
thanks for checking.

hope they implement this feature soon on iphone/ipad.
