### ISSUE TITLE
Not receiving push on ios 10 beta

### ISSUE THREAD

**Issue by Alexintosh** [Pushwoosh/pushwoosh-phonegap-plugin#187]
Works fine on ios >= 7 && <=10 and android as well. Can't really find any clue, no errors at all.

**Comment by DimanAM** [comment]
Pushwoosh plugin should work on iOS10 beta as usual. Make sure you have enabled **Push Notifications** in **Capabilities** section in XCode 8 beta.
If this does not help please attach device logs.

**Comment by CookieCookson** [comment]
Is there any way of doing this without fiddling in Xcode? e.g. through a CI environment where it builds from repo to IPA.

**Comment by DimanAM** [comment]
Fixed in 6.4.0.
