### ISSUE TITLE
iOS The app references non-public selectors in Payload

### ISSUE THREAD

**Issue by elysiopires** [Pushwoosh/pushwoosh-phonegap-plugin#188]
Hello Pushwoosh team,

When I validate the code to submit the app to apple, I received the warning: The app references non-public selectors in payload

I removed the Pushwoosh plugin and validation works fine without warnings.

Could you check it ASAP?

Sincerely,
Elysio

**Comment by DimanAM** [comment]
You can safely ignore this warning (at least for Pushwoosh plugin).
We plan to fix it in the nearest release to stop confusing other developers.

**Comment by DimanAM** [comment]
Fixed
