### ISSUE TITLE
Check to see if Notifications are enabled/disabled

### ISSUE THREAD

**Issue by dagmawim** [Pushwoosh/pushwoosh-phonegap-plugin#194]
Is there a way to do a device check to see if notifications are enabled/diabled for a Javascript Phonegap application? I was hoping there might be a method in this SDK but I wasn't able to find one. 

I also tried using this plugin with phonegap-plugin-push (https://github.com/phonegap/phonegap-plugin-push) to use its 'hasPermissions' method, but it had some very weird effects like the GCM (on Android) was only sending the notification to be handled by the phonegap-push-plugin. 

I was hoping to know if there was a way to check the device for enabled/disabled notifications or a way to integrate the above two plugins without it having any unexpected effects on the application?

**Comment by DimanAM** [comment]
For iOS you can use [getRemoteNotificationStatus](https://rawgit.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/master/Documentation/files/PushNotification-js.html#PushNotification.getRemoteNotificationStatus). 
On Android this will be added soon.

If you want to use Pushwoosh plugin along with `phonegap-plugin-push` you will need to remove `com.adobe.phonegap.push.*` services from AndroidManifest.xml.

**Comment by DimanAM** [comment]
Implemented in 6.0.0
