### ISSUE TITLE
IBM Mobilefirst 7.1 Cordova-iOS  Push notification crash the app

### ISSUE THREAD

**Issue by mohanrajskdev** [Pushwoosh/pushwoosh-phonegap-plugin#195]
Hi,
While receiving push notification getting crashed when app in active mode. Even if the app was background/minimized mode also crashing while open app from push notification.
Am getting below logs while crash the application.

**_FYI : It's only happened after update worklight version Worklight6.2 toMobilefirst 7.1._**

**2016-07-27 12:02:42.893 SAMPLE[797:152299] [PW] [I] -[PWRequestManager] 
x
|    Pushwoosh request:
| Url:      https://cp.pushwoosh.com/json/1.3/pushStat
| Payload:  {"request":{"hash":"v","hwid":"xxx-xxxx-xxx","userId":"xxx-xx-xxx","application":"xxx-xxxx","v":"4.0.4.","device_type":1}}
| Status:   "200 no error"
| Response: {"status_code":200,"status_message":"OK","response":null}
x
2016-07-27 12:02:42.895 SAMPLE[797:152299] [PW] [D] -[PushNotificationManager] sendStats completed
2016-07-27 12:02:43.280 SAMPLE[797:152086] [FATAL] [WORKLIGHT] Uncaught Exception: **\* -[__NSArrayI objectAtIndex:]: index 1 beyond bounds [0 .. 0]
2016-07-27 12:02:43.291 SAMPLE[797:152086] **\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayI objectAtIndex:]: index 1 beyond bounds [0 .. 0]'
**\* First throw call stack:
(0x23735f8f 0x32082c8b 0x236487a5 0x161c7f 0x16171f 0x2446f36d 0x236fbcbf 0x236fb83b 0x236f9a8b 0x23645f31 0x23645d43 0x2b120201 0x26e17879 0x44fb3 0x32634aaf)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)*\*

**Comment by DimanAM** [comment]
What version of Pushwoosh plugin do you use?
Can you please provide crash logs with call stack?

**Comment by mohanrajskdev** [comment]
Hi DimanAM, I was used old one , after meet the crash issue., i was update the latest (download now and update)**PushNotification.h and PushNotification.m., also add a new file PWLog.h**.
