### ISSUE TITLE
Windows Phone push-notification event not firing

### ISSUE THREAD

**Issue by Lecramed** [Pushwoosh/pushwoosh-phonegap-plugin#199]
Hi, we can register our device on windows Phone (10)
but we don't seem to receive a push notification event.
We receive the notification. or the tile update.
But we cant handle the incoming message inside the app.

We user Cordova and the Telerik Appbuilder Verified plugin 6.0.0 version.

**Comment by endriazizi** [comment]
Hi there, do you know where can I get those data?

<img width="1280" alt="screen shot 2016-09-01 at 23 00 58" src="https://cloud.githubusercontent.com/assets/9431994/18185263/095595c0-709d-11e6-9e80-a7ed2c9c86d8.png">
<img width="1280" alt="screen shot 2016-09-01 at 23 00 44" src="https://cloud.githubusercontent.com/assets/9431994/18185264/0964dd82-709d-11e6-97ef-2229d53d87e2.png">
<img width="1280" alt="screen shot 2016-09-01 at 23 01 07" src="https://cloud.githubusercontent.com/assets/9431994/18185265/09659330-709d-11e6-9c21-a53127755f41.png">

**Comment by wfhm** [comment]
We've investigated the issue and it looks related to Telerik Appbuider, not Cordova. We have put adding a separate Appbuilder plugin in our pipeline so as soon as it is done we will update you in this thread.

**Comment by wfhm** [comment]
Fixed in 7.1.0.
