### ISSUE TITLE
[NEED HELP] How to configure pushwoosh for Windows Phone Universal

### ISSUE THREAD

**Issue by endriazizi** [Pushwoosh/pushwoosh-phonegap-plugin#200]
Hello,
How can I get those data what are in the following screens?

<img width="1280" alt="screen shot 2016-09-01 at 23 00 58" src="https://cloud.githubusercontent.com/assets/9431994/18185484/25d20b92-709e-11e6-88bd-8a0a8a8d6839.png">
<img width="1280" alt="screen shot 2016-09-01 at 23 00 44" src="https://cloud.githubusercontent.com/assets/9431994/18185485/25d589de-709e-11e6-9728-a513e78a66b0.png">
<img width="1280" alt="screen shot 2016-09-01 at 23 01 07" src="https://cloud.githubusercontent.com/assets/9431994/18185486/25da9e88-709e-11e6-8b61-b209b836a735.png">

**Comment by wfhm** [comment]
Hi, since this issue in not directly related to the plugin, it is better to resolve it with our Support team via http://pushwoosh.com/contact-us
