### ISSUE TITLE
The app references non-public selectors in Payload ... errorMessage

### ISSUE THREAD

**Issue by guirip** [Pushwoosh/pushwoosh-phonegap-plugin#202]
Hello

When uploading an iOS app (or simply click 'Validate' from the Xcode 'Organizer' window) the following warning appears :
_The app references non-public selectors in Payload/MYAPPNAME.app/MYAPPNAME: errorMessage:_

This results in **app rejection** when trying to publish it to production !

This seems pretty new as we released a 1.0 version of our app last month without encountering this warning.

Although we found no occurrence of the string 'errorMessage' in the plugin source code (except in spec/test-runner.js which does not seem related to the warning message), it is precisely when we add this pushwoosh cordova plugin that the warning appears. We tried with releases 5.1.3 et 6.2.0 with same result.

Could this come from the binary PushWoosh which appears in the 'Link Binary with Libraries' section ?
Can you reproduce it and can we hope any quick fix ?

Thanks a lot

**Comment by guirip** [comment]
PS: Asked for some more details, this is what Apple Store Review team replied :

_"errorMessage:" was found in [PWZipArchive outputErrorMessage:]_

**Comment by DimanAM** [comment]
Fixed in 6.2.1
