### ISSUE TITLE
Can I use Google FCM with this?

### ISSUE THREAD

**Issue by tomflanagan** [Pushwoosh/pushwoosh-phonegap-plugin#204]
Hello,

I have noticed one of our apps have been getting very few opens. In fact our test devices are only sporadically getting the notifications. I started to upgrade the pushwoosh account to use Google FCM because I thought that GCM might not be performing as well.  I linked the FCM account to the app. This did not change the sender id or anything like that. So my questions are.

1. Does this plugin support FCM?
2. Do I have to make any code changes?

**Comment by shaders** [comment]
1. Yes. The only difference: Pushwoosh Android Push-Payload is different from FCM notification payload (which FCM library uses to generate the notification).

2. No. There are no code changes.

You are saying your test devices receive the notifications sporadically. I would recommend to contact our support team in this case. They are the best to help.
