### ISSUE TITLE
Duplicate Android.xml meta-data 

### ISSUE THREAD

**Issue by acti0nm4n** [Pushwoosh/pushwoosh-phonegap-plugin#205]
Plugin added: cordova plugin add pushwoosh-cordova-plugin --variable IOS_FOREGROUND_ALERT_TYPE="ALERT" --variable ANDROID_FOREGROUND_PUSH="true"

When building it seems to add them again but as undefined values:
        <meta-data android:name="PW_LOG_LEVEL" android:value="undefined" />
        <meta-data android:name="PW_NO_BROADCAST_PUSH" android:value="undefined" />

Or clearing the Android manifest completely:
        <meta-data android:name="PW_LOG_LEVEL" android:value="undefined" />
        <meta-data android:name="PW_NO_BROADCAST_PUSH" android:value="undefined" />
        <meta-data android:name="PW_NO_BROADCAST_PUSH" android:value="true" />

**Comment by viridanti** [comment]
Hi,

The solution was described in this thread - https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/216
