### ISSUE TITLE
IOS 10

### ISSUE THREAD

**Issue by tomflanagan** [Pushwoosh/pushwoosh-phonegap-plugin#207]
We just got a notification from pushwoosh and was wondering how this would affect this plugin. See below:

> Due to the changes in iOS 10 you need to upgrade your Pushwoosh iOS SDK as soon as possible. The latest version 4.1.2 of the SDK is fully compatible with iOS 10 devices.
> 
> In order to exclude any discrepancies and keep your push campaigns up and running please make sure you have the latest version of Pushwoosh iOS SDK.

**Comment by shaders** [comment]
You need to update to the latest plugin version which include 4.1.2 iOS SDK. Thanks!
