### ISSUE TITLE
missing pushToken on iOS

### ISSUE THREAD

**Issue by mccraigmccraig** [Pushwoosh/pushwoosh-phonegap-plugin#209]
i'm on 

cordova 6.3.1
cordova ios 4.2.1
pushwoosh-cordova-plugin 6.2.1

sometimes my app isn't getting a pushToken from pushwoosh

my understanding thus far is that it happens when sequential app installs come from XCode and then TestFlight

removing the app completely and then re-installing makes the issue go away - the app gets a pushToken

any thoughts ?

thanks!

**Comment by DimanAM** [comment]
Is `registerDevice` error callback getting called? Have you enabled `Push Notifications` capability using XCode? 
TestFlight uses AdHoc provisioning profile thus it needs **production** `aps-environment` in project entitlements.

**Comment by mccraigmccraig** [comment]
apologies - this is a race condition in my code, nothing to do with pushwoosh plugin :blush:
