### ISSUE TITLE
ios 10 push-notification event not fire and yes it working fine in android

### ISSUE THREAD

**Issue by mobileias** [Pushwoosh/pushwoosh-phonegap-plugin#210]
Hello

I have one issues comes since last one day same code working fine in both ios and android now when i build again after that push-notification event not fire when push come or when click on push from notification in ios 10.0.2 device cordova is 3.9.1. I am using latest pushwoosh plugin

All is fine in android .
`<preference name="phonegap-version" value="cli-5.2.0"/>`
`<gap:plugin name="pushwoosh-pgb-plugin" source="npm" version="6.2.1"/>`

Thanks in advance

**Comment by StefanoMagrassi** [comment]
Same issue and it's driving me crazy...

Unlike @mobileias I'm using cordova 6.3.1 (and the latest version of the plugin)

**Comment by mobileias** [comment]
I have noticed something different type for this issue

If i turn ON Debug Mode ON from https://cp.pushwoosh.com/v2/notifications for particular application then it will working fine and when it automatic turn OFF then push event not called so something wrong when we send push from API.

**Comment by beck24** [comment]
I also had this same problem, have been in contact with pushwoosh and they have apparently fixed it as of today.  So we need the latest SDK pulled into the cordova plugin.

**Comment by shaders** [comment]
Could you please try 6.2.2. It should include the latest iOS SDK. (4.1.5)

**Comment by beck24** [comment]
6.2.2 seems to be working on cursory tests, thanks!

**Comment by shaders** [comment]
👍

**Comment by mukesh-igdinaction** [comment]
I could still see the issue in IOS. It works fine in Android. I tried both latest and 6.2.2 cordova plugin on ios. Can someone let me know any issue with IOS 10.2 and possible workaround ?
