### ISSUE TITLE
 icon badge not showing after using latest pushwoosh plugin from npm in android

### ISSUE THREAD

**Issue by mobileias** [Pushwoosh/pushwoosh-phonegap-plugin#211]
i have one issue while using latest pushwoosh plugin using from npm As before badge set working fine for both os (ios and android ) for pushwoosh version 3.6. Now after using 
`<preference` name="android-build-tool" `value="gradle"/>` and 
`<gap:plugin name="pushwoosh-pgb-plugin" source="npm" version="6.2.1"/>`

it not able to set badge icon for android 5 lollipop version

Any one please give me solution for this.?

Thanks in andvance

**Comment by DimanAM** [comment]
What is the device model? Is icon badge not showing for [setApplicationIconBadgeNumber](https://rawgit.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/master/Documentation/files/PushNotification-js.html#PushNotification.setApplicationIconBadgeNumber) and/or remote notifications?

**Comment by mobileias** [comment]
Yes both way it not set icon badge using setApplicationIconBadgeNumber or direct when any unread push notification in app 
Android version is 5.1.1
Model is : Sony C6902

**Comment by DimanAM** [comment]
Got this reproduced. Support for Sony as well as HUAWEI, ZUK and OPPO will be added in the nearest release.

**Comment by mobileias** [comment]
thank you so much

Once fix let me know Sir.

**Comment by DimanAM** [comment]
Fixed in 6.3.0

**Comment by mobileias** [comment]
Thank you so much.
Now it working fine.
