### ISSUE TITLE
not receiving any pushwoosh msg after update cordova plugin

### ISSUE THREAD

**Issue by int3rnet** [Pushwoosh/pushwoosh-phonegap-plugin#213]
Dear is pushwoosh 

i have report this issue via email and twitter , the pushwoosh was working just fine , i updated the cordova plugin to newest version and changed the javascript file with new one (taken from pushwoosh website) , after building the app , the xcode console showing /registerDevice working fine and gave me a new token without any error , but after sending the pushwoosh from CP , i don't receive anything + showing invalid token 

i changed the device + i used another appliction and same issue 

below the pic for xcode console 

https://s10.postimg.org/d0hfte6rt/Screen_Shot_2016_10_14_at_9_09_23_PM.png

message ID : 2123491269 , 2123479620 , 2123479476 , 2123297370 , 2120383576

dears this is urgent issue and impact my business very much

**Comment by shaders** [comment]
Hi,

I've forwarded this to the team. Please note this is not a support forum, here we can discuss the API, methods, integration, etc. I'm closing the ticket now.
