### ISSUE TITLE
PushWoosh_LogLevel won't keep the debug level

### ISSUE THREAD

**Issue by rwillett** [Pushwoosh/pushwoosh-phonegap-plugin#216]
Hi,

Since we upgraded from PushWoosh 4.2.2 to PushWoosh 6.2.6, we've noticed that the debug flag 
```
Pushwoosh_LOG_LEVEL
```
won't keep the state we set it at it for iOS.

e.g. 

We set the flag
![screen shot 2016-10-27 at 06 38 13](https://cloud.githubusercontent.com/assets/668923/19755799/03072faa-9c10-11e6-8993-d26ebf9ddb6b.png)

We do a command line build
```
cordova build ios
``` 
and without updating anything else in the project, indeed just leaving the .plist open it gets changed to undefined

![screen shot 2016-10-27 at 06 39 39](https://cloud.githubusercontent.com/assets/668923/19755830/43e9e6f2-9c10-11e6-959a-30f645b15f09.png)
 Whilst this is not the worlds greatest bug, it's a pain having to change it when theres no need to.

Thanks

Rob

**Comment by DimanAM** [comment]
This is related to this problem https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/203. `cordova plugin add pushwoosh-cordova-plugin --save` will set all unspecified preferences to `undefined` not the default values from plugin.xml.

As a workaround you can set `LOG_LEVEL` explicitly:
`cordova plugin add pushwoosh-cordova-plugin --variable LOG_LEVEL="NONE" --save`

Or you can modify `config.xml` manually after adding plugin.

**Comment by rwillett** [comment]
Thank for this.

We've just tried setting ```config.xml``` with 

```
  <plugin name="pushwoosh-cordova-plugin" spec="~6.2.6">
    <variable name="LOG_LEVEL" value="NONE" />
    <variable name="IOS_FOREGROUND_ALERT_TYPE" value="undefined" />
    <variable name="ANDROID_FOREGROUND_PUSH" value="undefined" />
  </plugin>
```
and it doesn't seem to work. Is this just for PhoneGap builds?

Rob

**Comment by DimanAM** [comment]
Have you tried to readd ios platform (and all plugins) after that?

**Comment by rwillett** [comment]
I'm sorry, but we don't understand what you mean.

Do you mean reinstall the plugin with the variable flag set?
```
cordova plugin add pushwoosh-cordova-plugin --save
```

Rob

**Comment by DimanAM** [comment]
>We've just tried setting config.xml with
>  ```xml
>  <plugin name="pushwoosh-cordova-plugin" spec="~6.2.6">
>    <variable name="LOG_LEVEL" value="NONE" />
>    <variable name="IOS_FOREGROUND_ALERT_TYPE" value="undefined" />
>    <variable name="ANDROID_FOREGROUND_PUSH" value="undefined" />
>  </plugin>
> ```
> and it doesn't seem to work.

Try removing `plugins` and `platforms` directories and run `cordova platform add ios`.

**Comment by rwillett** [comment]
OK, removing platforms and reinstalling platforms and plugins seems to make the LOG Level stick

Thanks

Rob
