### ISSUE TITLE
Module not found error - pushwoosh in Java version 1.8

### ISSUE THREAD

**Issue by roymj88** [Pushwoosh/pushwoosh-phonegap-plugin#217]
Hi guys,

Implemented pushwoosh in my hybrid app and it worked fine for iOS version. 

However for android i had to update Java version to 1.8 from 1.6. But from that time, the push notification plugin seems to be not found. The project code base is same. Just the Java version has been upgraded to 1.8.

```
var pushNotification = cordova.require("pushwoosh-cordova-plugin.PushNotification"); 'undefined'
```

Removed platform, plugins and tried adding back again. Doesn't work. Can someone confirm that the plugin do not have any dependancy with Java version? Especially 1.6 and 1.8? 
- Java version **"1.8.0_102"**
  Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
  Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
- Cordova Version : **6.3.1**

**cordova plugin list**

```
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
pushwoosh-cordova-plugin 6.2.6 "Pushwoosh"
```

**cordova platform list**

```
Installed platforms:
  android 5.2.2
  ios 4.2.1
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0
```
#185 seems to be similar, but was closed without having found a proper solution.

Is there any solution for this?

**Comment by shaders** [comment]
Do you see anything suspicious in build logs?

Check platforms/platform_name/www/cordova_plugins.js
Do you see the plugins there?

What do you see in:
var md = cordova.require("cordova/plugin_list").metadata;

Have you also tried Cordova 6.4.0 (released 2 days ago)?

**Comment by roymj88** [comment]
@shaders 

```
Check platforms/platform_name/www/cordova_plugins.js
```
and 
```
var md = cordova.require("cordova/plugin_list").metadata;
```
surely lists our pushwoosh plugin. 

**Regarding 6.4.0** - No i dint yet try that. Will give it a shot and let you know. 

Really weird issue creeping me out.
