### ISSUE TITLE
 Unable to start receiver com.pushwoosh.local.BootReceiver in pushwoosh 6.2.2 plugin for galaxy s7 Android os

### ISSUE THREAD

**Issue by mobileias** [Pushwoosh/pushwoosh-phonegap-plugin#222]
Hello We have around 20+ apps using pushwoosh 6.2.2 plugin version and phonegap cli 6.3.0 .
`<preference name="phonegap-version"           value="cli-6.3.0" />`
`<plugin name="pushwoosh-pgb-plugin" source="npm" version="6.2.2"/>`
We have seen error like

`java.lang.RuntimeException: Unable to start receiver com.pushwoosh.local.BootReceiver: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Set at android.app.ActivityThread.handleReceiver(ActivityThread.java:3641) at android.app.ActivityThread.access$2000(ActivityThread.java:221) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:158) at android.app.ActivityThread.main(ActivityThread.java:7224) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) `
`Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Set at android.app.SharedPreferencesImpl.getStringSet(SharedPreferencesImpl.java:234) at com.pushwoosh.local.a.a(Unknown Source) at com.pushwoosh.local.a.a(Unknown Source) at com.pushwoosh.local.BootReceiver.onReceive(Unknown Source) at android.app.ActivityThread.handleReceiver(ActivityThread.java:3634) ... 8 more`

in galaxy S7 like below type error. http://prntscr.com/d22yaa

So any one help me for this type issue.

**Comment by wfhm** [comment]
Fixed in 6.3.1
