### ISSUE TITLE
 window.plugins.pushNotification.setEnableLED(true) is without effect

### ISSUE THREAD

**Issue by RonnySchleicher** [Pushwoosh/pushwoosh-phonegap-plugin#225]
### Steps to reproduce
1. create new fresh cordova app with the pushwooh plugin

```
cordova create PhoneGap_android de.test.test Test
cd PhoneGap_android
cordova platform add android
cordova plugin add https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin.git 
...
```

2. Add the code to initialize the plugin

```
var pushNotification = window.plugins.pushNotification;
pushNotification.setEnableLED(true, function(){
         console.log('okay');
}, function () {
         console.log('error');
});
pushNotification.setMultiNotificationMode();
pushNotification.onDeviceReady({ projectid : 'XXXX', appid : 'YYYYY' });
pushNotification.registerDevice(....
```

### Problems
* the callbacks in **setEnableLED** are never called
* the LED is never blicking if a push notification received

### Environment
* Latest Coradova Version with the latest Pushwoosh plugin
* actuale Android Studio
* Testdevice is a Nexus 5X with Android 7.0

**Comment by wfhm** [comment]
Hey,

I've just tested the code you provided and it is indeed not working if notification is sent without `'led'` key value specified, however with a specified value for it it works as expected. Could you please try sending some notifications via Control Panel with LED parameter checked (see screenshot attached) and let us know about the results?

![screen shot 2016-11-17 at 18 28 40](https://cloud.githubusercontent.com/assets/13344781/20389442/2a3e56be-acfc-11e6-9afb-8116ee09c92c.png)

**Comment by RonnySchleicher** [comment]
Thank you for your quick response. I will test it and then report it again.

**Comment by RonnySchleicher** [comment]
Sorry for the late reply.
Your tip was right.
Thanks for your help.
