### ISSUE TITLE
READ_PHONE_STATE and pushwoosh

### ISSUE THREAD

**Issue by boynet** [Pushwoosh/pushwoosh-phonegap-plugin#229]
seems like [old issue](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/79)

how to reproduce:
1. create hello world app with no plugins and check permissions see that there are nones.
2. add pushwoosh plugin and see read_phone_state permission.

is it some bug or intended behavior? if intended where is this permissions asked for? I want to remove it manually if its possible

**Comment by boynet** [comment]
looks like its coming from  play-services
[https://commonsware.com/blog/2015/06/25/hey-where-did-these-permissions-come-from.html](https://commonsware.com/blog/2015/06/25/hey-where-did-these-permissions-come-from.html)

**Comment by shaders** [comment]
I suppose I can close this?
