### ISSUE TITLE
Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by mobileias** [Pushwoosh/pushwoosh-phonegap-plugin#231]
We are currently facing issue like 
http://prnt.sc/dibrwd

Since last 8th Dec 2016 till now.

As previous just one day we have already created new build and it working fine.
Just after one day we rebuild with same type code and app give above type error.
Any one have solution please ?

**Comment by wfhm** [comment]
Hi, 

Do you have Push Notifications enabled both for your provisioning profile on Apple Developer Portal and in XCode?
