### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by MaicolBen** [Pushwoosh/pushwoosh-phonegap-plugin#233]
A issue reported by crashalytics : `Unable to instantiate receiver com.pushwoosh.MessageAlertReceiver: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.MessageAlertReceiver"`

Do you know what could be?

**Comment by shaders** [comment]
This is a class for Amazon push notifications support. Do you have any info on which device this is happened and what SDK version do you use?

**Comment by MaicolBen** [comment]
Weird because it happens on Android 4.3.1 (Motorola Defy Mini XT320), the versions are:
- pushwoosh-phonegap-plugin version 6.4.0 
- cordova android version  5.1.1 
- cordova version 6.2.0
- android sdk version 19

**Comment by wfhm** [comment]
Fixed in 6.5.0.
