### ISSUE TITLE
Name on PushWoosh notification is an old name

### ISSUE THREAD

**Issue by rwillett** [Pushwoosh/pushwoosh-phonegap-plugin#236]
Hi,

We have an unusual situation that we can't work out how to resolve. We don't know if its PushWoosh, IOS, Apple or the phases of the moon. Apologies if this is obvious but we've been scratching our head for a week on and off trying to fix it.

Background

We have created a new app that is now called "Tunnelbuster". This is now the name in the config.xml file 

``` <name>Tunnelbuster</name> ```

The app **used** to be called "JambusterBT" in development until we worked out its new name. So we had 

``` <name>JambusterBT</name>``` 

in our config.xml file. 

When we send a notification the Pushwoosh console the message comes up like this

We see **JambusterBT** on the top of the notification group, the name "Tunnelbuster" underneath it and our simple PushWoosh test message. 

![img_2600](https://cloud.githubusercontent.com/assets/668923/22140389/18c7e930-dee4-11e6-8cc9-54f7132cde00.PNG)

We cannot work out how to change "JambusterBT" to "Tunnelbuster". This is the same on IOS 8,9 and 10.

We know this is not a REST API issue from us as we get the same problem sending a test notification from the PushWoosh console.

What we have done:

1. Removed and reinstalled the cordova plugin for 6.4.1. We had that version before.
2. Checked the config.xml file is correct 
3. Removed and reinstalled the cordova IOS plugin. We were running cordova-ios@4.3.1 and still are running cordova-ios@4.3.1
4. Grepped for the string in the whole of the root directory ```find . -type f -exec grep JambusterBT "{}" /dev/null \;```. This produces nothing
5. Checked the PushWoosh console and can't see any configuration item called "JambusterBT".
6. Looked through the Apple Push certificates to see if it is embedded somehow in there. We cannot recall what we did when we created the certificates. However we cannot see anything in the Apple certificates but that means nothing :)
7. Checked as much as we can the certificates in the Keychain Access.
8. Uninstalled the app on the iPhone's and reinstalled. 

Clearly we have set the app to JambusterBT sometime in the past but we are at a loss of how to change it to the new name. Our gut feeling is that we did this in the certificates somehow which is the worst possible case as we hate setting all the certificates up.

Any suggestions or pointers welcomed.

Thanks

Rob

**Comment by rwillett** [comment]
We've deleted and recreated the PushWoosh app in the PushWoosh configuration and we still get "JambusterBT" in the notification header. 

This is looking more like a Apple certificate issue as we are at a loss as to what else it could be.

Any ideas?

Thanks

Rob

**Comment by rwillett** [comment]
Wer managed to get rid of this issue by starting again and creating a new app certificate, new provisioning certificates and basically redoing the whole app registration.

A complete pain in the arse.

Rob

**Comment by shaders** [comment]
Yes, the problem is that name comes from the app itself. You did the right thing in the end... thanks Apple.

My another guess would be working this around with Info.plist, changing the value of CFBundleDisplayName field.
