### ISSUE TITLE
Android - Unfortunately, <App Name> has stopped.

### ISSUE THREAD

**Issue by gabaum10** [Pushwoosh/pushwoosh-phonegap-plugin#239]
I'm using version 6.4.1 and I don't see any mentions of this.  

When the user force kills the app, a popup comes up and says "Unfortunately, *App Name* has stopped."  I have narrowed it down through the process of elimination to be this plugin that's causing the error.  I have no idea why that would be.

I have no way of debugging this because it's too late for the traditional debug tools.  Has anyone else reported this?

**Comment by gabaum10** [comment]
I'm using cordova 6.3.1 and cordova Android 5.2, building from the command line.

**Comment by gabaum10** [comment]
Or maybe I'm doing something wrong with my initializer?  



    var pushNotification = cordova.require("pushwoosh-cordova-plugin.PushNotification");    
    pushNotification.setMultiNotificationMode();

    //set push notifications handler
    document.addEventListener('push-notification', function (event) {
        var userData = event.notification.userdata;
        // get the data
        if(!userData) {
            if(event.notification.ios) {
                // try to get the data from the fallback
                try {
                    event.notification.userData = JSON.parse(event.notification.ios.u);
                } catch(ex) {
                    // invalid JSON
                }
            } else if(event.notification.android) {
                // android handler
                try {
                    event.notification.userData = JSON.parse(event.notification.android.u);
                } catch(ex) {
                    // invalid JSON
                }
            }
            // no valid data, skip
            if(!event.notification.userData) { return ; }
        }
        // handle the push notification event in app
        processPushNotification(event.notification);

        if (typeof (userData) != "undefined") {
            console.warn('user data: ' + JSON.stringify(userData));
        }
    });

    //initialize Pushwoosh with projectid: "GOOGLE_PROJECT_NUMBER", pw_appid : "PUSHWOOSH_APP_ID". This will trigger all pending push notifications on start.
    pushNotification.onDeviceReady({projectid: "P_ID", pw_appid: "PW_APPID"});
    //register for pushes
    var registrationAttempts = 1; // counter for retrying the registration process
    var registerDevice = function() {
        pushNotification.registerDevice(
            function (status) {
                var token = status.pushToken;
                if(!token) {
                    logErr('Push token is undefined, something is wrong', 'WARN');
                    return;
                }
                app.deviceManager.device.set('pushToken', token);
                registerDeviceToken(token, function () {
                    console.warn('push token: ' + token);
                }, function (error) {
                    console.log(error);
                });
            },
            function (status) {
                // if we have a legit error, we want to try again every second 5 times in case it was a network hiccup or something
                if(typeof status.error !== 'string' || !status.error.includes('disabled by user')) {
                    if(registrationAttempts <=5) {
                        setTimeout(function() {
                            registrationAttempts++;
                            registerDevice();
                        }, 1000);
                    } else {
                        registrationAttempts = 0;
                        logErr('Failed to register user device with pushwoosh after 5 attempts: ' + JSON.stringify(status));
                    }
                }
            });
    };

    registerDevice();`

**Comment by gabaum10** [comment]
Also, have you guys tested everything in a crosswalk environment?  That's the only think that I can think of that might be causing conflicts.  I'm using the [Cordova Crosswalk Plugin](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview).

**Comment by gabaum10** [comment]
I dropped the version of the pushwoosh plugin to 5.0.0 for comparison purposes, and it didn't throw the error.  I guess I could just do a binary search through the versions until I find the one that broke it...

**Comment by gabaum10** [comment]
Ok, I narrowed it down to the release that introduced the bug.

It was something from release 6.2.6 to 6.3.0.  6.2.6 works correctly.

**Comment by wfhm** [comment]
Hi, 

Could you please provide us with a bit more details on your issue? Particularly, when exactly is this error message shown: right after a user force stops your app or when he relaunches it?

Also please provide us with your device console log with the moment when this alert is shown captured?

**Comment by gabaum10** [comment]
The error message in the title is the exact error message.  `Unfortunately, <App Name> has stopped.`.  It happens immediately after the user force kills it.  For example, open up the list of running apps and swipe it right to kill it.  Or say Kill all, something like that.  

Which logs do you want?  The one from the chrome developer tools?

**Comment by viridanti** [comment]
Hi,

It would be helpful to see the logs from the device itself, illustrating the crashes, specifically the `stack trace` from `adb logcat `. Thanks!

**Comment by gabaum10** [comment]
Weird, I just updated to the latest (6.4.2) and it's not happening anymore.  Now, I did update cordova CLI to  version 6.5.0 at some point since I opened this issue.  That may have helped too.  I was on like 6.2.x or maybe even lower.
