### ISSUE TITLE
Suggestion for Doc update

### ISSUE THREAD

**Issue by rwillett** [Pushwoosh/pushwoosh-phonegap-plugin#240]
Hi,

Unsure where the best place is for this. I looked for something on the server side/console documentation but nothing seemed obvious.

We've just reconfigured our Cordova app for production pushes. We had previously set it up just for development and for pushes to the app when setup from Xcode. 

There are two areas where the docs could be clearer, or even present :) This is all to do with auto reconfiguration of Apple Push servers.

1. Its not clear to us about the differences between the sandbox and production Pushwoosh environments. Which should be used and when. We grepped through various forums and got a sense of what it was but we're still unsure now if the 'new' Apple certificates cover development and production and how PushWoosh fits in. We *think* that we should only need to provide one certificate now but we're unsure.

2. Once we *think* we have done it correctly, we sent a couple of test notifications from the PushWoosh dashboard and nothing turned up. Our initial assumption is that we have got step 1 wrong, whereas the real reason is that it takes some time for things to work and that our configuration is correct, it's just something behind the scenes is working away and as if by magic X minutes later, things work (for some value of X more than 5 minutes). We checked by turning debug on and looking at the reports and it said invalid token which tended to make us thing we had misconfigured, when we hadn't.

These are the things that would have helped us enormously earlier today. Just to be clear things are working the way we *think* they should be :)

Thanks

Rob

**Comment by viridanti** [comment]
Hi,

Thanks for your suggestions! We recommend to email our support team regarding docs and/or configuration. I've forwarded it to them already.

Regards,
Andrey
