### ISSUE TITLE
Cordova 6.5.0 Push notifications only come through when app is closed

### ISSUE THREAD

**Issue by microchipmatt** [Pushwoosh/pushwoosh-phonegap-plugin#242]
Hello.  When using the cordova pushwoosh plugins.  Notifications only come through when the app is closed... If the app is open, and in the forground, it receives no notifications....

**Comment by viridanti** [comment]
Hi,

By default, Pushwoosh Cordova plugin does not display pushes if the app is in the foreground. Could that be the case? Please refer to our docs for more info - http://docs.pushwoosh.com/docs/customizing-cordova-plugin#push-notifications-in-foreground

Regards,
Andrey
