### ISSUE TITLE
Confused by IOS sandbox vs production - What's the workflow?

### ISSUE THREAD

**Issue by rwillett** [Pushwoosh/pushwoosh-phonegap-plugin#243]
Hi,

We've currently got an app that is working very well with PushWoosh. We've been using it for over a year, it works with the sandbox and with production. Indeed it works so well, we've never really thought about it :)

We've just created a new app which we also have 'more or less' working with PushWoosh but it appears to have limitations in how it interacts with PushWoosh. 

Our first app was manually configured for notifications and used certificates that we managed to work out over a year ago. We believe we managed to create ad-hoc certificates for our first app (without realising) which meant that PushWoosh worked well for development and in production. We just assumed that this was the way it should work. 

Our second app has been a nightmare, we have no issue with getting it working with either Pushwoosh sandbox OR Pushwoosh development but if we configured for development, we could see notifications in our apps that were pushed from Xcode and if we downloaded beta builds from Testflight, we couldn't see the development notification. If we set PushWoosh for production, our development app doesn't receive notifications but our production app does. 

We *think* but cannot confirm as the documentation from Apple is utter, utter junk (as per normal) that we need to create ad-hoc provisioning profiles and use those on our new app. We *think* but cannot confirm that this is what we mistakenly did for our first app which is why we had no issues. 

So for our second app we have been trying to get it to work with zero success. We can have either sandbox and local apps or production and Testflight delivered apps. Clearly having to wait for Apple to process apps for Alpha testing is utter nonsense as we do 10-15 builds per hour sometimes to test things out, especially when we are testing the server backend.

After three days of pulling our hair out and screaming at each other we have given up trying to create ad-hoc provisioning profiles for our second app. So we created a third app to try this out from the beginning. Utter failure, two more days of reading StackOverflow, hating and loathing Apple for forcing their vile certificates on us and more screaming and shouting at each other in the team. We must have created 50-60 certificates and read dozens of blogs, websites and watched video all promising to easily create ad-hoc certificates with absolutely no results. 

So we have tried a different tack, we have created a fourth PushWoosh app, this one dedicated to development. It targets the same bundle Id for the third app, but the 3rd PushWoosh app is production and the fourth PushWoosh app is sandbox. This seems to work but is a waste of a PushWoosh app. We have ten we can use, so we could flick one PushWoosh app around as we work on a project, so we have nine PushWoosh apps. 

Overall this has been a nightmare, we have wasted a dozen days of the teams time, trying to get Ad-Hoc certificates in and failing miserably. We accept that Apple certificates have beaten us, we are not sure who are supposed to use ad-hoc certificates but they are clearly a higher evolved super intelligent alien life form, but not us. 

So my question is, is there another way to get notifications out to apps running off Xcode AND off testFlight without having to waste a PushWoosh app? We know we can reconfigure the PushWoosh app to move to sandbox, but that stops production working OR are we expected to have a second PushWoosh app devoted to development or a pre-production environment. The PushWoosh docs are remarkably light on this subject. 

Any advice or guidance welcomed, I have to go now, one of the team is screaming in pain after reading yet another page on certificates. 

BTW Google push notifications just work.

Thanks

Rob

**Comment by wfhm** [comment]
Hi Rob,

Since your issue is not directly related to Pushwoosh Phonegap plugin, in order to resolve it timely we recommend you to submit a ticket for our Support team:

https://www.pushwoosh.com/contact-us

**Comment by rwillett** [comment]
I will raise it there.
