### ISSUE TITLE
Attempt to invoke virtual method 'void com.pusahwoosh.PushManager.registerForPushNotifications()' on a null object reference" error

### ISSUE THREAD

**Issue by TejasJN** [Pushwoosh/pushwoosh-phonegap-plugin#250]
This is the Error log i am getting in Android mobile for Unity Pushwoosh plugin
This is for Remote push notification in unity( for Android Devices)
"Attempt to invoke virtual method 'void com.pushwoosh.PushManager.registerForPushNotifications()' on a null object reference"
Please anyone help me in this

**Comment by wfhm** [comment]
Hi,

This is a wrong place to ask this question. As far as we know you have already had a conversation with our Customer Support Engineer via email channel and have still not replied the questions addressed to you. Could you please provide them with a **full** device log with **full** stack trace of your issue?
