### ISSUE TITLE
'UserNotifications/UserNotifications.h' file not found

### ISSUE THREAD

**Issue by maury91** [Pushwoosh/pushwoosh-phonegap-plugin#252]
I'm trying to compile an application with this plugin and I get the following:

```
▸ Compiling PushNotification.m

❌  /Users/vagrant/git-build/platforms/ios/Oasis/Plugins/pushwoosh-cordova-plugin/ios/PushNotificationManager.h:10:9: 'UserNotifications/UserNotifications.h' file not found

#import <UserNotifications/UserNotifications.h>
^
```

Installed on the virtual machine:
Node: 6.0.0
NPM: 2.15.9
Cordova: 6.1.1
Cordova iOS: 4.1.1
Pushwoosh: 6.5.2

**Comment by DimanAM** [comment]
Pushwoosh plugin requires XCode 8.x. What version of XCode do you use?

**Comment by maury91** [comment]
I'm using XCode 7.x, I will try to update to XCode 8, thanks

**Comment by 2intor** [comment]
hi
