### ISSUE TITLE
<br>, <strong> tag or any html tag not working in ios push notification.

### ISSUE THREAD

**Issue by mobileias** [Pushwoosh/pushwoosh-phonegap-plugin#253]
Hello Sir

We are using phone gap build site for creating apk and ipa . 

`<preference name="phonegap-version"           value="cli-6.5.0" />`
and also using latest pushwoosh plugin

`<plugin name="pushwoosh-cordova-plugin" source="npm" version="6.5.2">`

Now while any custom html tag in push notification it not parse in ios and shows like below screenshot type.
http://prntscr.com/fh9huk
It works fine in android device.

So can you please give any solutions for this .

Thanks in advance.

**Comment by wfhm** [comment]
Hi,

There is no rich text functionality in iOS Push Notifications, so any HTML tag will be shown as a plain text. It is a natural iOS limitation, and, unless Apple changes it, we can do nothing with it.
