### ISSUE TITLE
Android build fails. Apparent conflict with other plugins

### ISSUE THREAD

**Issue by rhengles** [Pushwoosh/pushwoosh-phonegap-plugin#254]
I'm having this problem using this plugin together with [cordova-plugin-facebook4 v1.9.1](https://github.com/jeduan/cordova-plugin-facebook4):

```
:processReleaseManifest/project/AndroidManifest.xml:27:9-38 Error:
	Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
	is also present at [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31 value=(25.3.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.
```

This came up when I upgraded cordova-plugin-facebook4 from v1.7.4 to v1.9.1.

I tracked this down and found this: https://github.com/jeduan/cordova-plugin-facebook4/issues/507

I [forked](https://github.com/rhengles/pushwoosh-phonegap-plugin/commit/d5391b5d9c9d1f65d97bf75b3e21caa056bc8df3) this project and changed this on `plugin.xml`:

```diff
-		<framework src="com.android.support:support-v4:+" />
+		<framework src="com.android.support:support-v4:25.+" />
```

And then my project on Phonegap Build ran successfully!

**Comment by DimanAM** [comment]
Fixed in 6.5.3
