### ISSUE TITLE
setApplicationIconBadgeNumber not working on samsung s7 on android 7

### ISSUE THREAD

**Issue by mccraigmccraig** [Pushwoosh/pushwoosh-phonegap-plugin#255]
i'm using pushwoosh-cordova-plugin 6.5.3 and setApplicationIconBadgeNumber is no longer working on my samsung s7 on android 7

there is a recent ShortcutBadger bug - leolin310148/ShortcutBadger#199 - which is perhaps the underlying cause

i also filed a bug report with pushwoosh-android-sdk : 

https://github.com/Pushwoosh/pushwoosh-android-sdk/issues/55

**Comment by wfhm** [comment]
Fixed in 7.0.0 version.
