### ISSUE TITLE
App Switches To Deep Link

### ISSUE THREAD

**Issue by lpender** [Pushwoosh/pushwoosh-phonegap-plugin#256]
Hi!

*Steps To Reproduce*

1) Open an app from an iOs device.
2) Send a push notification to this device with a deep link (i.e. `myapp://mylink`)

*Actual Result*

- The link `myapp://mylink` opens immediately in the app.

*Expected Result*

- Should see the notification at the top of the screen. 
- Tapping the notification should open the link.

**Comment by wfhm** [comment]
Hi,

Could you please specify whether you have a **Pushwoosh_ALERT_TYPE** flag in your info.plist with a **NONE** value?

**Comment by wfhm** [comment]
@lpender 

Could you please let us know if you had a chance to review my previous comment? Is this issue still persistent?
