### ISSUE TITLE
Android Oreo (8.0) Support

### ISSUE THREAD

**Issue by rtwall** [Pushwoosh/pushwoosh-phonegap-plugin#260]
After upgrading to Oreo, I no longer receive notifications.

Guessing it has something to do with:

_Apps cannot use their manifests to register for most implicit broadcasts (that is, broadcasts that are not targeted specifically at the app)._
- https://developer.android.com/about/versions/oreo/android-8.0-changes.html#atap

I'll dig a bit deeper, but if there are updates planned, please let me know.

**Comment by wfhm** [comment]
Hi,

Just tried to reproduce the issue and everything is working fine, pushes are received correctly. Could you please provide us with a bit more info on the issue? What is not working exactly? Some logs or a particular error message would be very useful to look at.

**Comment by rtwall** [comment]
Push events were not firing on my Google Pixel / Android 8.0.0.

It's working for me now after upgrading what I could in our (Ionic 1) project.  No idea what the root cause was though.

Thank-you for taking a look @wfhm.

**Comment by ajaybhalerao12** [comment]
I am not able to receive push notification on my Google Pixel / Android 8.0.0.
Do i need to upgrade the "phonegap-plugin-push" to latest version?
Current version used: phonegap-plugin-push 1.10.4 "PushPlugin"

I am using ionic 1 app which is already deployed on play store.

**Comment by rtwall** [comment]
@ajaybhalerao12 - ionic1 with the latest version ([7.0.7](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/releases/tag/7.0.7)) works on Oreo
