### ISSUE TITLE
registerDevice, clicking 'Don't Allow' does not fire success error callback on IOS

### ISSUE THREAD

**Issue by egonzalez-T** [Pushwoosh/pushwoosh-phonegap-plugin#263]
When registerDevice is called clicking 'Allow' works correctly but click 'Don't Allow' does not execute any callback and call hangs.

**Comment by wfhm** [comment]
Hi,

Checking this.

**Comment by wfhm** [comment]
@egonzalez-T 

Got it reproduced only with **Remote notifications** background mode turned off. Please make sure that you have both **Push notifications** and **Remote notifications** background mode enabled in XCode Capabilities tab.

**Comment by vveysner** [comment]
@egonzalez-T please recheck capability
<img width="704" alt="c1d05a8-pushnotificationsapp_xcodeproj" src="https://user-images.githubusercontent.com/30684306/31094029-da01e282-a7dd-11e7-990a-456520bd0118.png">
![2726836-screen_shot_2016-09-20_at_14 39 50](https://user-images.githubusercontent.com/30684306/31094034-e0a6e31c-a7dd-11e7-8e49-0f8299fb98a2.png)

**Comment by egonzalez-T** [comment]
@wfhm @vveysner Confirmed this was the issue. Thank you.
