### ISSUE TITLE
Cant receive silent push on android SDK 6.5.3

### ISSUE THREAD

**Issue by Lecramed** [Pushwoosh/pushwoosh-phonegap-plugin#268]
Hi,

We can't seem to receive silent push messages from pushwoosh to our android device.
Normal messages are being received just fine. We use the pushwoosh test page in the pushwoosh portal.

We use version 6.5.3 because if we import > 7 we can't build anymore.
We use telerik appbuilder to build our solution.

Can anybody help me?

Greetings
Marcel de Groot

**Comment by wfhm** [comment]
Hi,

Will check it. Meanwhile could you please describe how exactly you send a silent push? 

Also, we had recently asked Telerik to update their plugin fork, and they seemingly did it - the latest commit to their fork was done in September and uses 7.0.5 version of the plugin - however there was no release rolled out, so it is a good idea to contact them and ask to add it.

**Comment by Lecramed** [comment]
Hi, I've also notified pushwoosh.

I'm sending the silent push using the pushwoosh portal. Checkmark the silent push

But also in code using the  
"android_silent": 1, // Optional. 0 or 1, enable silent notificaiton (ignore sound and content) 

both not working for android "ios_silent" is working

When i import the 7.0.5 version from telerik verified plugins i can't build 

`Platform=Android
ProjectConfiguration=debug
AcceptResults=Url;LocalPath
BuildConfiguration=debug
Framework=Cordova
FrameworkVersion=6.4.0
AndroidArchitectures=armv7
LiveSyncToken=s5sKNWeCD+17IdMIEkfTaoP7zK1VuKYYTLMYXSvh/EiukjUzqSrwrntQcdBS2JGU1TKYsUaZcufaWcciiWvjd2PU1YzYq3DVeq1wjbtglCM=.
[2017-10-17 08:56:40.815] Log (Exception,High): Server build failed. Server output: Project "ELGAPP.tmp.proj" (default targets):
               Warning: Cannot include the following item(s) in your application: Plugins\cordova-diagnostic-plugin-master\.gitignore;Plugins\cordova-imagePicker-master\.gitignore;Plugins\cordova-plugin-file-master\.github\PULL_REQUEST_TEMPLATE.md;Plugins\cordova-plugin-file-master\.gitignore;Plugins\cordova-plugin-file-master\.jshintrc;Plugins\cordova-plugin-file-master\.ratignore;Plugins\cordova-plugin-file-master\.travis.yml;Plugins\cordova-plugin-file-master\www\blackberry10\.jshintrc;Plugins\cordova-plugin-file-transfer-master\.github\PULL_REQUEST_TEMPLATE.md;Plugins\cordova-plugin-file-transfer-master\.gitignore;Plugins\cordova-plugin-file-transfer-master\.jscsrc;Plugins\cordova-plugin-file-transfer-master\.jshintrc;Plugins\cordova-plugin-file-transfer-master\.travis.yml;Plugins\cordova-plugin-file-transfer-master\www\blackberry10\.jshintrc;Plugins\cordova-plugin-globalization-master\.github\PULL_REQUEST_TEMPLATE.md;Plugins\cordova-plugin-globalization-master\.gitignore;Plugins\cordova-plugin-globalization-master\.jshintignore;Plugins\cordova-plugin-globalization-master\.jshintrc;Plugins\cordova-plugin-globalization-master\.ratignore;Plugins\cordova-plugin-globalization-master\.travis.yml;Plugins\cordova-plugin-globalization-master\src\blackberry10\native\.cproject;Plugins\cordova-plugin-globalization-master\src\blackberry10\native\.project;Plugins\cordova-plugin-globalization-master\src\windows\GlobalizationProxy\GlobalizationProxy\.gitignore;Plugins\cordova-plugin-whitelist-master\.github\PULL_REQUEST_TEMPLATE.md;Plugins\CordovaCallNumberPlugin-master\.npmignore;Plugins\google-analytics-plugin-master-wilson\.editorconfig;Plugins\google-analytics-plugin-master-wilson\.gitignore;Plugins\Pushwoosh-master\.gitignore;Plugins\SQLite-master\.gitignore;Plugins\SQLite-master\.travis.yml;Plugins\SQLite-master\spec\.cordova\config.json;Plugins\SQLite-master\spec\platforms\.gitignore;Plugins\SQLite-master\spec\plugins\.gitignore. The build system treats items with a leading dot as hidden files or directories and does not process them. If you want to include these items in your application package, rename them and rebuild your app.
               android Build Tooling revision 2017.08.15.1r
               Build Tooling Hostname b890de687721
               Warning: Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
               Warning: Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
               Warning: /mnt/storage/builds/cw0p25IPpUzffPgZTY/app/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
               Warning: /mnt/storage/builds/cw0p25IPpUzffPgZTY/app/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
               Warning: FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
               Warning: * Try:
               Warning: Run with --stacktrace option to get the stack trace. Run with --info
               Warning: or --debug option to get more log output.
               Warning: Error: /mnt/storage/builds/cw0p25IPpUzffPgZTY/app/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/mnt/storage/builds/cw0p25IPpUzffPgZTY/app/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
    
/mnt/storage/builds/cw0p25IPpUzffPgZTY/app/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/mnt/storage/builds/cw0p25IPpUzffPgZTY/app/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
               Error: Build failed during execution
               Error: 'Build failed with error code 2'
               Error: 'Build failed with error code 2'
Done building project "ELGAPP.tmp.proj" -- FAILED.`

**Comment by wfhm** [comment]
@Lecramed any news on this one?
