### ISSUE TITLE
IOS build fails: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by androdel** [Pushwoosh/pushwoosh-phonegap-plugin#269]
Hi,

I'm using the latest version of the Pushwoosh plugin, but if I want to build on iOS I get this message: Path must be a string. Received undefined. Android app builds perfectly. Anybody got any idea?

Cordova @ 7.1.0
iOS @ 4.5.2

Kind regards

**Comment by wfhm** [comment]
Hi,

Could you please provide us with a bit more details on this issue? A full build log or some screenshots would be much appreciated.

**Comment by mccraigmccraig** [comment]
i had the exact same error message but with android@6.2.3 and android@6.3.0 rather than iOS

downgrading cordova to 7.0.1 and removing/re-adding the platforms and the pushwoosh-cordova-plugin solved it. the error only occurred with cordova-7.1.0 and pushwoosh-cordova-plugin - i tried both 7.0.4 and 7.0.7

i couldn't get any detailed error messages out of the cordova build - --stacktrace and --debug didn't seem to give any more detail

**Comment by androdel** [comment]
Yep, downgrading Cordova to 7.0.1 also did the trick for me. I’ve also tried previous releases of pushwoosh plugin but without success. It seems that is error is coming from Cordova but relates on something of the pushwoosh plugin. Maybe their release notes of version 7.1.0 can help figure out where the problem lies?

**Comment by mccraigmccraig** [comment]
don't know @itpverde - i don't have any real insight into what is causing the error - i couldn't get any detailed error messages out of cordova

i had removed by node_modules, platforms and plugins directories and let prepare re-create them, but otherwise i have nothing to offer :(

**Comment by itpverde** [comment]
Finally worked by downgroading cordova to 7.0.1 [[AND ALSO Pushwoosh plugin to 7.0.6]].

Thanks for your help anyway. Regards,

Dani

**Comment by shivan** [comment]
Same problem here. Hopefully there will be an update for the pushwoosh plugin soon.

Using Cordova 7.1.0
npm 3.10.10
nodejs 6.11.0
xcode 9.0.1

**Comment by wfhm** [comment]
@itpverde pushwoosh-cordova-plugin@7.0.7 requires XCode 9, could it be the issue? Also, if you use Phonegap Build tool, you are not able to use @7.0.7, as Adobe have not yet updated XCode on their build servers.

**Comment by wfhm** [comment]
@shivan 

Checking the issue with pushwoosh-cordova-plugin and Cordova 7.1.0. Will update shortly.

**Comment by wfhm** [comment]
@shivan 
We tried reproducing the issue with no luck - it builds and runs just fine with pushwoosh-cordova-plugin@7.0.8 and Cordova 7.1.0. 

May I ask you to try our [Sample app](https://github.com/Pushwoosh/pushwoosh-phonegap-cordova-sample/tree/master/Cordova) and let us know whether the issue is reproducible with it on your side?

**Comment by robobobo** [comment]
I seem to be having a similar issue, everything works fine until I add the pushwoosh plugin

 `Installing "pushwoosh-cordova-plugin" for ios

Error: Path must be a string. Received undefined

[ERROR] Exception: `

I'm using the latest version of ionic/cordova etc..

`cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : ios 4.5.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2 
    Node       : v6.11.2
    npm        : 5.5.1 
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55 `

Everything works perfectly fine until I add the pushwoosh plugin the I get 'Error: Path must be a string. Received undefined' each time I try run 'ionic cordova build' 

Strangely if I remove the pushwoosh plugin I'll continue to get the problem, I have to remove the iOS platform and start again to get things working

I'm going to experiment with an older version of pushwoosh and see if that has any affect

**Comment by robobobo** [comment]
Tried with pushwoosh version 6.5.3 which previously was working fine, something must not be playing right with the updated ionic/angular/cordova frameworks

**Comment by robobobo** [comment]
Ok another update, I just set up a new ionic app completely blank, installed pushwoosh plugin and it built the iOS platform without any problems! Will keep digging!

**Comment by robobobo** [comment]
So an update, it turns out this was nothing to do with Pushwoosh but the error was caused by some code in my 'config.xml' file

I had 
` <config-file parent="UISupportedInterfaceOrientations~ipad" platform="ios" target="*-Info.plist">
            <array>
                <string>UIInterfaceOrientationLandscapeLeft</string>
                <string>UIInterfaceOrientationLandscapeRight</string>
                <string>UIInterfaceOrientationPortrait</string>
                <string>UIInterfaceOrientationPortraitUpsideDown</string>
            </array>
        </config-file>`

In my config.xml file and once I removed it this removed the error completely. Luckily this isn't something I need anymore as it's just a setting in Xcode, obviously support for it has been dropped!

Once I removed that code from my config.xml file, it all complied as expected

**Comment by wfhm** [comment]
@robobobo Thank you for letting us know!

**Comment by pugwonk** [comment]
I'm having this problem too (and I don't have anything odd looking in my `config.xml`). Cordova 7.1.0, XCode 9.2, pushwoosh-cordova-plugin 7.0.8.

Behavior is I think the same as @robobobo. Build fails with "Error: Path must be a string. Received undefined". If I run `cordova platform rm ios` and then `cordova platform add ios`, it gets as far as "Installing pushwoosh-cordova-plugin for ios" and then shows me that same error and stops. If I remove the ios platform, then run `cordova plugin rm pushwoosh-cordova-plugin`, then re-add the ios platform, it all works fine and the build runs. If I then run `cordova plugin add pushwoosh-cordova-plugin`, the plugin does seem to install okay but all my builds fail immediately with that error. Adding -d to the build command doesn't tell me anything enlightenning (the item immediately before the error is "Prepared iOS project successfully"). Again much like @robobobo (and somewhat mysteriously), if I then remove the pushwoosh plugin my builds continue to fail with the same error until I remove and re-add the ios platform again.

It definitely seems to be something that's caused/triggered by the Pushwoosh plugin, but the error also seems to live on after uninstalling it.

**Comment by wfhm** [comment]
@pugwonk Could you please provide us with your build log? Also, may I ask you to try using **pushwoosh-pgb-plugin** instead of **pushwoosh-cordova-plugin**?

**Comment by robobobo** [comment]
After reading @pugwonk 's post that behaviour is exactly what was happening to me. It was the mysterious issue with builds failing even after the plugin was removed, and then sometimes the builds work would fine depending on the order I added the platform or plugin.

My conclusion of it being an issue with the config.xml file was probably more out of desperation than anything!

**Comment by pugwonk** [comment]
@wfhm I'm not using PhoneGap - should I still try using the pgb plugin?

**Comment by wfhm** [comment]
@pugwonk I've re-read your previous message, and realized that it will not solve the issue, as it happens even with 6.5.3 version of the plugin.

We could not reproduce the issue on our side with Cordova 7.1.0 and XCode 9.2 yet. By any chance could you please provide us with your full build log?

**Comment by jopache** [comment]
We also had issues with this plugin and this error.  Using Cordova 7.1.0 and Pushwoosh plugin 7.1.0 . it does not require a full build to recreate the issue.  A simple Cordova prepare will make the issue come up.

**Comment by wfhm** [comment]
@androdel @mccraigmccraig @itpverde @shivan @robobobo @pugwonk @jopache 

Guys, could you please let us know whether the issue persists with the latest version of the plugin?

**Comment by shivan** [comment]
Hi,

on our side it's now working after removing several settings in the config.

**Comment by pugwonk** [comment]
We're still seeing this in Cordova 7.1.0 and 8.

**Comment by MatthewPringle** [comment]
I have just seen this problem when adding camera plist settings to config.xml

Could this plugin be getting confused with other settings in the config.xml file, such as

```
<config-file target="*-Info.plist" parent="NSCameraUsageDescription"     <string>CAMERA_USAGE_DESCRIPTION</string>
</config-file>
```

**Comment by narenderreddych** [comment]
yes Still seeing this issue in pushwoosh latest (7.9.4) and cordova 8.0 in iOS platform
