### ISSUE TITLE
Skip/disable Location and Bluetooth Permissions

### ISSUE THREAD

**Issue by sandstrom** [Pushwoosh/pushwoosh-phonegap-plugin#270]
How can we disable or skip the location and bluetooth permissions that this plugin adds to our Android manifest?

We're not using this functionality and would like to limit the number of permissions we request from our users.

**Comment by wfhm** [comment]
Hi,

These permissions should not automatically be added to your project if you use the latest pushwoosh-cordova-plugin version, therefore could you please specify which plugin version is in question?

**Comment by sandstrom** [comment]
@wfhm This was 7.0.4. With 7.0.8 these permissions aren't added. Thanks!
