### ISSUE TITLE
Android receiving notifications twice

### ISSUE THREAD

**Issue by mehmetkoc182** [Pushwoosh/pushwoosh-phonegap-plugin#271]
My app receives every notification twice for some reason.
What's interesting is one of the notifications has all the extra information(additional data, logo URL etc.) and the other only has the message.

Is anybody else having the same problem?

**Comment by wfhm** [comment]
Hi,

We could not reproduce the issue on our side, so may I ask you to provide us with a reproducer? You can send it via this form:

pushwoosh.com/contact-us/

**Comment by mehmetkoc182** [comment]
Thanks! Talking to the help team now.
