### ISSUE TITLE
App crashes when it starts.

### ISSUE THREAD

**Issue by Manmade** [Pushwoosh/pushwoosh-phonegap-plugin#277]
I build with phonegap build and I get no build errors but the app crashes when I try to open it.
It works with the first below on the iPhone, but not on Android.

Im using this in my config file:
preference name="phonegap-version" value="cli-7.0.1" 
plugin name="pushwoosh-cordova-plugin@7.2.3" source="npm" 

and I also have tested with the same as I build an old app with that worked before:
preference name="phonegap-version" value="cli-6.5.0" 
gap:plugin name="pushwoosh-pgb-plugin" source="npm" 

But both crashes on the Android when I try to start the app.
Im testing it on an old Samsung galaxy S4. With Android version 5.0.1
Please, what cli and plugin should I use for Android?
Thanks!

**Comment by wfhm** [comment]
Hi,

Could you please share your device console logs describing the crash?

Also, could you please specify whether you use Phonegap Build cloud tool to build your app or is it any other framework (like Ionic, Telerik Appbuilder or any other)?

**Comment by Manmade** [comment]
Hi wfhm, thanks.
Im using the phonegap build tool and the appid is 2888688.
Tha apk file is here https://www.manmade.se/iphone/skolappen/SKOLAPPEN-release.apk if you want to test it. Im not sure where I can see the logs for the crash on the phone?

**Comment by Manmade** [comment]
I finnalt found out that if I used plugin 7.0.1 it works on Android!
