### ISSUE TITLE
Cordova 8.0.0 Android 7.0.0 build warning

### ISSUE THREAD

**Issue by Plurilogic** [Pushwoosh/pushwoosh-phonegap-plugin#283]
Here's a warning thrown for the pushwoosh plugin when building with cordova 8.0.0 android 7.0.0

`:app:transformClassesWithDesugarForDebug
MSBUILD : cordova-build warning : warning: Ignoring InnerClasses attribute for an anonymous inner class
2>MSBUILD : cordova-build error : (com.pushwoosh.inbox.internal.a.c) that doesn't come with an
2>MSBUILD : cordova-build error : associated EnclosingMethod attribute. This class was probably produced by a
2>MSBUILD : cordova-build error : compiler that did not target the modern .class file format. The recommended
2>MSBUILD : cordova-build error : solution is to recompile the class from source, using an up-to-date compiler
2>MSBUILD : cordova-build error : and without specifying any "-target" type options. The consequence of ignoring
2>MSBUILD : cordova-build error : this warning is that reflective operations on this class will incorrectly
2>MSBUILD : cordova-build error : indicate that it is *not* an inner class.`

**Comment by wfhm** [comment]
Hi,

Checking it.

**Comment by anibalsanchez** [comment]
This issue and #284 seem to be related.

**Comment by wfhm** [comment]
@anibalsanchez 
Will be fixed with the next release.

**Comment by wfhm** [comment]
@anibalsanchez fixed with 7.4.0.
