### ISSUE TITLE
Apps crashing on launch - Android 6

### ISSUE THREAD

**Issue by shauntrennery** [Pushwoosh/pushwoosh-phonegap-plugin#286]
With the latest version, v7.3.1, apps running on Android 6 crash on launch. Seems to be related to 

`<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />`

being commented out in plugin.xml

**Comment by wfhm** [comment]
Hi,

You should manually add the following permissions as per [this guide](https://pushwoosh.readme.io/v1.0/docs/customizing-cordova-plugin#section-geozones-push-notifications):

```
<!--<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />-->
<!--<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />-->
<!---->
<!--<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />-->
```
