### ISSUE TITLE
7.3.1 builds fail for Ionic with Crosswalk

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-plugin#287]
A showstopper for us. No such issue with 7.2.5 plugin for example.
Here's part of the log:

```
:transformClassesWithDexForArmv7Releasewarning: Ignoring InnerClasses attribute for an anonymous inner class
(com.pushwoosh.inbox.internal.a.c) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Release'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/design/widget/CoordinatorLayout$1;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.932 secs
Command finished with error code 1: /app/platforms/android/gradlew cdvBuildRelease,-b,/app/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Dorg.gradle.jvmargs=-Xmx2048m,-Pandroid.useDeprecatedNdk=true
Error: /app/platforms/android/gradlew: Command failed with exit code 1 Error output:
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.pushwoosh.inbox.internal.a.c) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Release'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/design/widget/CoordinatorLayout$1;
```

**Comment by wfhm** [comment]
@zarko-tg 

> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/design/widget/CoordinatorLayout$1;

Both 7.2.5 and 7.3.1 versions use com.android.support:26.+ version of this lib, and 7.3.1 specifies `<framework src="com.android.support:design:26.+" />` in its plugin manifest, so if there is any other plugin using a different version, it leads to this build issue.

Therefore, could you please check if you have any other plugins using Android Support library? If building locally, you can edit plugin.xml to specify a particular version to be used, however please note that Pushwoosh SDK will only work with 26+ version (as it is required for Android 8 push notification support).

**Comment by zarko-tg** [comment]
Not quite sure what's going on here since no other plugins on our project specify the dependency in their plugin.xml.

**Comment by wfhm** [comment]
@zarko-tg 

Very strange. Is there a possibility to provide us with a simple reproducer project? Also, could you please share your output for `cordova plugin` command?

**Comment by zarko-tg** [comment]
No reproducer project so far.
Here's the output you asked for:
cordova-fabric-plugin 1.1.10 "cordova-fabric-plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-globalization 1.0.8 "Globalization"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-ms-adal 0.10.1 "ADAL for Cordova"
cordova-plugin-screen-orientation 2.0.2 "Screen Orientation"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.1 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
pushwoosh-cordova-plugin 7.3.1 "Pushwoosh"

Let me repeat that this issue is a problem only when building for Crosswalk, and not pure Android.

**Comment by wfhm** [comment]
@zarko-tg 

If you build locally and do not use Pushwoosh Inbox feature, you can try the following workaround:

* Install pushwoosh-cordova-plugin via npm
* Open plugin.xml and remove the following frameworks:

```
<framework src="com.pushwoosh:pushwoosh-inbox:5.7.2"/>
<framework src="com.pushwoosh:pushwoosh-inbox-ui:5.7.2"/>
<framework src="com.android.support:appcompat-v7:26.+" />
<framework src="com.android.support:recyclerview-v7:26.+" />
<framework src="com.android.support:design:26.+" />
<framework src="com.android.support.constraint:constraint-layout:1.0.2" />
```

**Comment by wfhm** [comment]
@zarko-tg Additionally, could you please check your build.gradle for Android platform and figure out if **com.android.support:design** lib is added and, if yes, which version is implemented?

**Comment by wfhm** [comment]
@zarko-tg have you had a chance to test the workaround above as well as to check if you have ** com.android.support:design** lib added in your build.gradle?

**Comment by zarko-tg** [comment]
Hi there, I'll come back to this in a day or so, was away from office.

**Comment by wfhm** [comment]
@zarko-tg any news?

**Comment by zarko-tg** [comment]
Let's see...

**Comment by zarko-tg** [comment]
No luck with this.

Here are the dependencies from build.gradle:
```
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile(project(path: "CordovaLib", configuration: "debug"))
    releaseCompile(project(path: "CordovaLib", configuration: "release"))
    compile "com.android.support:support-v4:26.+"
    compile "com.android.support:appcompat-v7:26.+"
    compile "com.google.android.gms:play-services-gcm:+"
    compile "com.google.android.gms:play-services-location:+"
    compile "com.google.firebase:firebase-core:+"
    compile "com.google.firebase:firebase-messaging:+"
    compile "com.android.support:recyclerview-v7:26.+"
    compile "com.android.support:design:26.+"
    compile "com.android.support.constraint:constraint-layout:1.0.2"
    compile "com.github.bumptech.glide:glide:4.3.1"
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:1.1.60"
    compile "com.pushwoosh:pushwoosh:5.7.2"
    compile "com.pushwoosh:pushwoosh-amazon:5.7.2"
    compile "com.pushwoosh:pushwoosh-badge:5.7.2"
    compile "com.pushwoosh:pushwoosh-gcm:5.7.2"
    compile "com.pushwoosh:pushwoosh-inbox:5.7.2"
    compile "com.pushwoosh:pushwoosh-inbox-ui:5.7.2"
    // SUB-PROJECT DEPENDENCIES END
}
```

Also, we don't use the Inbox feature. Tried removing those frameworks from plugin.xml but still getting build failure.
```
* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Release'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: Cannot merge new index 68876 into a non-jumbo instruction!
```

**Comment by wfhm** [comment]
@zarko-tg 

    * What went wrong:
    Execution failed for task ':transformClassesWithDexForArmv7Release'.
    > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: Cannot merge new index 68876 into a non-jumbo instruction!

Looks like your final apk contains more than 65k objects in DEX files. Did you try enabling jumbo mode in your build.gradle to override this limit?

```
android {
    ...
    dexOptions {
        jumboMode true
    }
}
```

Some background on the issue: 

https://stackoverflow.com/questions/21490382/does-the-android-art-runtime-have-the-same-method-limit-limitations-as-dalvik/

**Comment by wfhm** [comment]
@zarko-tg any luck with enabling Jumbo mode?

**Comment by zarko-tg** [comment]
Sorry, no more time planned to spend on this. Maybe we reopen if needed. Until then we'll try to stick to the older Pushwoosh plugin version.

**Comment by wfhm** [comment]
@zarko-tg Got it.

Please feel free to reopen the issue when there will be any updates.
