### ISSUE TITLE
7.4.0 Android builds fail

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-plugin#289]
:compileArmv7ReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/app/platforms/android/src/com/pushwoosh/plugin/pushnotifications/PushNotifications.java:662: error: lambda expressions are not supported in -source 1.6

                GDPRManager.getInstance().removeAllDeviceData(result -> {
                                                                     ^
  (use -source 8 or higher to enable lambda expressions)

1 error

**Comment by wfhm** [comment]
@zarko-tg Fixed in 7.4.1
