### ISSUE TITLE
Build failed:  Could not find com.android.support

### ISSUE THREAD

**Issue by darkcreative** [Pushwoosh/pushwoosh-phonegap-plugin#291]
Hi all,

i cannot build android after adding the pushwoosh cordova plugin. Build android leads to following errors, but Android Support Repository is installed.

Could not find com.android.support.constraint:constraint-layout:1.0.2.
Could not find com.android.support:support-annotations:26.0.2.

I just checked the other cordova plugins, but pushwoosh is the first plugin which uses the support library. Does anyone have an idea? Thanks.

Cordova plugins used:
        "pushwoosh-cordova-plugin@7.4.1",
        "cordova-plugin-crosswalk-webview@1.7.0",
        "cordova-plugin-network-information@1.2.1",
        "cordova-plugin-whitelist@1.2.2",
        "cordova-plugin-file-opener2@2.0.2",
        "cordova-plugin-file@4.2.0",
        "cordova-plugin-file-transfer@1.5.1",
        "ionic-plugin-keyboard@2.0.1",
        "cordova-sqlite-storage@1.4.1",
        "cordova-plugin-camera@2.3.0",
        "cordova-plugin-image-picker@1.1.1",
        "com-badrit-base64@0.2.0",
        "cordova-plugin-device@1.1.6",
        "cordova-plugin-splashscreen@3.2.2",
        "cordova-plugin-device-motion@1.2.5",

**Comment by wfhm** [comment]
Hi,

Could you please provide a bit more details on your environment? Are you building your app locally? Which version of Cordova and which version of Gradle are used? Also, could you please provide your output for `cordova requirements`?

**Comment by darkcreative** [comment]
The app is build locally. Cordova version 6.5.0, Grade version 2.2.1.

Requirements check results for android:
Java JDK: installed .
Android SDK: installed 
Android target: installed android-21,android-22,android-23,android-25,android-27,Google Inc.:Google APIs:22,Google Inc.:Google APIs:23
Gradle: installed

**Comment by brandecho** [comment]
Hi @darkcreative I am also having similar issues, but you may want to also check the recent updates for this plugin as of 21 days ago (ver 7.4.1). According to the [README.md](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin), using npm (requires cordova 7.0+). Secondly, although the plugin.xml has not been updated to reflect the latest version of the .jar files (com.pushwoosh:pushwoosh:5.7.2), you may continue to have issues with the latest version of this plugin as I noticed the [Android SDK](https://github.com/Pushwoosh/pushwoosh-android-sdk) has been updated 3 days ago. The are over 96 changed files with 148 additions and 148 deletions and I noticed that the .jar files have been updated to ver [5.7.3](https://github.com/Pushwoosh/pushwoosh-android-sdk). Hopefully the Cordova plugin will be updated soon to reflect this change.

**Comment by wfhm** [comment]
@darkcreative 

Is the issue still reproducible with the latest plugin version?
