### ISSUE TITLE
Feature proposal: Pushwoosh for Flutter / Dart

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-plugin#292]
Perhaps you could put this request in your product line / plan for development.

**Comment by wfhm** [comment]
@zarko-tg 

Hey, we are already working on adding Flutter support. Once the plugin is released, I will update you via this thread.

**Comment by zarko-tg** [comment]
That's good to hear @wfhm.

**Comment by wfhm** [comment]
@zarko-tg Hey, 

We have rolled out the initial release of Pushwoosh Flutter plugin, please have a look:

https://pub.dartlang.org/packages/pushwoosh
