### ISSUE TITLE
Phonegap Build fails on Build...

### ISSUE THREAD

**Issue by plantastika** [Pushwoosh/pushwoosh-phonegap-plugin#294]
I´m using:

<gap:plugin name="pushwoosh-pgb-plugin" source="npm" />

PGB says: Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: pushwoosh-cordova-plugin

---
PhoneGap (iOS / Android / Windows)
4.3.1 / 6.3.0 / 4.4.3

**Comment by wfhm** [comment]
Hi,

Just tested it with the latest version and it worked fine for me. Could you please clarify which plugin version were you using and whether the issue is still persistent?

**Comment by plantastika** [comment]
I get the code  from the website guide

<gap:plugin name="pushwoosh-pgb-plugin" source="npm" />

Which is the correect?

**Comment by wfhm** [comment]
@plantastika 

Got the issue. The fix will be applied as soon as pushwoosh-inbox package is moved out as a separate plugin.
