### ISSUE TITLE
 Notifications are not coming on Android Oreo

### ISSUE THREAD

**Issue by hitenzaptech** [Pushwoosh/pushwoosh-phonegap-plugin#295]
Hello,
I am using pushwoosh plugin for pushnotification in my cordova phonegap application.
Actually the issue is that notifications are not coming in the Android O devices.

Cordova Android Platform is :: **4.1.1**
Pushwoosh Plugin version :: **6.3.0**

can you please help me out to solve this issue.

Android 8 is using Notification channel, so how to implement channel code in pushwoosh.

**Comment by wfhm** [comment]
@hitenzaptech Hey,

6.3.0 plugin version is very outdated and was published long before Android O official release. It does not support notification channels required for Android 8 as well as new background processing flow. Please update to the latest plugin version and let us know about the results.

**Comment by hitenzaptech** [comment]
@wfhm any specific version or the latest one ?

**Comment by hitenzaptech** [comment]
@wfhm I tried but it's not working.
Actually I can't update the plugin directly because it's used differently.
So I replace the files of the latest version and then check it but it's not working.

**Comment by wfhm** [comment]
@hitenzaptech could you please provide us with a device log using the new version of the plugin (including application open, registration and a moment of expected push reception)? 

Also, could you please describe the update issue in a bit more details? Is there any error message in the build log?

At last, did you try to reproduce the issue with our [Sample app](https://github.com/Pushwoosh/pushwoosh-phonegap-cordova-sample)? Can you receive notifications on your Android 8 devices with this app?

**Comment by wfhm** [comment]
@hitenzaptech Any news on the build issue?

**Comment by wfhm** [comment]
Closed until there is more information to work with.

**Comment by dread-pirate-bob** [comment]
@wfhm what would the equivalent pushwoosh-xamarin verison be?

**Comment by wfhm** [comment]
@dread-pirate-bob It should be 5.0.4, however this is version was released more than a year ago, so we highly recommend using the latest one.
