### ISSUE TITLE
Cordova Android build fails

### ISSUE THREAD

**Issue by tiepp** [Pushwoosh/pushwoosh-phonegap-plugin#297]
Hello,
we use Cordova to build iOS and Android versions of our app. The iOS build runs perfectly fine. However the Android build fails with the error:

`TypeError: Path must be a string. Received undefined`

Without the Pushwoosh plugin the build is successful.

I have found the issue  #269 which seems to describe our problem. However it is referring to iOS and it is closed already. 

I have also found hints that `<config-file>` tags need to have the target attribute. As a workaround I monkey patched your plugin by removing these directives
`<config-file>
   <access origin="*.pushwoosh.com" />
</config-file>`
from the plugin.xml and do the whitelisting inside our own config.xml.

Our package versions:
cordova: 8.00
cordova-android: 7.0.0
cordova-ios: 4.5.5
cordova-plugin-whitelist: 1.3.3
pushwoosh-cordova-plugin: 7.8.7

**Comment by tiepp** [comment]
The build succeeds now after I rebuilt the cordova project from scratch. However I still get these warnings:

`config file undefined requested for changes not found at /myapp/cordova/platforms/android/undefined, ignoring`

I assume these are related to this issue

**Comment by rjelierse** [comment]
Might be related to a [change](https://issues.apache.org/jira/browse/CB-13770) introduced with cordova-common 2.2.3 which now triggers warnings when a config file is not found and `<config-file>` entries in `plugin.xml` which don't name a specific target?

**Comment by clewsk8er** [comment]
I manually put 
<access origin="*.pushwoosh.com" />
in my config.xml file then removed the platforms. Commented out this section
<config-file>
     <access origin="*.pushwoosh.com" />
</config-file>

then re-added platforms and built with no warnings.

**Comment by wfhm** [comment]
@clewsk8er @rjelierse @tiepp Hello guys,

We've checked it and it seems there is no way to fix these warnings from Pushwoosh SDK side. However it looks like all SDK functionalities are working fine, so basically it does not affect anything. Could you please confirm it, or describe the issues you had noticed while having your apps built with these warnings?

**Comment by rjelierse** [comment]
@wfhm 
No real issue, just the warning messages. I merely wanted to shed a light on the possible cause of the warnings, as they might throw people off. You might still want to look into the empty `<config-file>` entries, as they don't seem to be doing anything (hence the warning message).
