### ISSUE TITLE
Cannot find plugin.xml for plugin "pushwoosh-cordova-plugin" Error

### ISSUE THREAD

**Issue by yecicen** [Pushwoosh/pushwoosh-phonegap-plugin#299]
Hi,
My environment details are :
Cordova : 8.1.2 (cordova-lib@8.1.1)
Android :  7.1.1
When I add "cordova plugin add pushwoosh-cordova-plugin" and then run the command "cordova platform add android", I get this error which says "Cannot find plugin.xml for plugin "pushwoosh-cordova-plugin". Please try adding it again.". Can you help me please ?

**Comment by wfhm** [comment]
@yecicen We were unable to reproduce it so far. Could you please let us know whether the issue persists, and, if it does, provide us with a simple reproducer?

**Comment by yecicen** [comment]
It was related to some other issue in our development system. We solved the issue now thanks.

**Comment by mohamedMobileSpot** [comment]
how u have solve it ?
