### ISSUE TITLE
incompatible block pointer types initializing 'CGFloat

### ISSUE THREAD

**Issue by xale76** [Pushwoosh/pushwoosh-phonegap-plugin#300]
just compiled and now I get this error on ios

/project/Visitami/Plugins/pushwoosh-cordova-plugin/ios/PWBackward.m:49:15: error: incompatible block pointer types initializing 'CGFloat (^__strong)(uint8_t)' with an expression of type 'double (^)(uint8_t)'
    CGFloat (^extractColor)(uint8_t) = ^(uint8_t byte){ return ((colorInt >> (byte * 8)) & 0xFF) / 255.; };

what is? last time I've compiled without problem, 2 weeks ago

**Comment by wfhm** [comment]
Hey @xale76 ,

This is fixed with the latest release (7.9.3)
