### ISSUE TITLE
Found firebase-messaging:+, but version 11.+ is needed for the google-services plugin.

### ISSUE THREAD

**Issue by webquali** [Pushwoosh/pushwoosh-phonegap-plugin#309]
Hi, I have installed Intercom plugin and pushwoosh then try to make a build. But have this error: Found firebase-messaging:+, but version 11.+ is needed for the google-services plugin.
I found <framework src="com.google.firebase:firebase-messaging:+" /> in pushwoosh config.xml

When I change to <framework src="com.google.firebase:firebase-messaging:11.+" /> then I haave success build.

**Comment by wfhm** [comment]
@webquali most of push notification providers use Firebase messaging library in their SDKs, however they might specify different versions of the lib. It is pretty much impossible to prevent conflicts with *all* plugins, so it the easiest solution is to solve the conflicts manually by modifying either Pushwoosh's or other plugin's config.xml

**Comment by webquali** [comment]
Ok, thanks. I already changed by self.
