### ISSUE TITLE
Cannot build on android (Path must be a string. Received undefined)

### ISSUE THREAD

**Issue by guirip** [Pushwoosh/pushwoosh-phonegap-plugin#313]
Hello

This issue is closely linked to this one I think:
https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/297#issuecomment-418101837

> config file undefined requested for changes not found at /work/mobile-spot/projects/testapp/platforms/android/undefined, ignoring
> Path must be a string. Received undefined
___
We had already encountered this kind of warning messages few month ago using pushwoosh-cordova-plugin, without consequence (like stated in above linked issue). Now that we need to customize AndroidManifest.xml using `<edit-config>` and  `<config-file>` tags, the warning has became a **blocking** problem.
___
**Simple steps to reproduce :**

- create a dummy cordova project `cordova create testapp && cd testapp`
- add android platform : `cordova platform add android@7.1.4`
- in config.xml, add a `<config-file>` to `<platform name='"android">`. Whatever the content, e.g:

        <config-file parent="/*" target="res/xml/config.xml">
            <preference name="android-minSdkVersion" value="15" />
        </config-file>

- execute `cordova prepare` then `cordova build`, it succeeds.

**Now:**

- add pushwoosh plugin: `cordova plugin add pushwoosh-cordova-plugin@7.13.0` (problem also appears with older versions like 7.9.4)
- execute `cordova prepare` and `cordova build`. There is no error but the cordova build commands returns 1, stopping the process.

```
> cordova build
Android Studio project detected
config file undefined requested for changes not found at /work/projects/testapp/platforms/android/undefined, ignoring
Path must be a string. Received undefined
>
```

Once we add pushwoosh-cordova-plugin we cannot build our android app anymore.

*edit 18/4/2019*
Cordova version:
```
> cordova -v
8.1.2 (cordova-lib@8.1.1)
```

**Comment by wfhm** [comment]
@guirip 

Just tried reproducing it following the steps you have described, and it indeed fails with cordova@8.1.2, however it works just fine with cordova@9.0.0. Could you please try upgrading Cordova CLI and let us know if the issue persists?

**Comment by wfhm** [comment]
@guirip did you have a chance to test it with the latest cordova version?

**Comment by guirip** [comment]
@wfhm 

Thank you for your answer :) Maybe you could write somewhere in bold characters that Cordova 9 is mandatory.

**Android**
Now the build process is OK, app runs well and we receive the pushes. :+1: 

**iOS**
We cannot build our app using Cordova 9 because it seems that some plugins does not support this cordova version, see: [Using "requireCordovaModule" to load non-cordova module "q" is not supported](https://github.com/apache/cordova/issues/85) :-1: 

So now we have to uninstall/reinstall cordova depending on the target platform. This is pretty cumbersome. **Is there any possibility that you produce a release compatible with Cordova 8 ?**

**Comment by wfhm** [comment]
Hi @guirip,

Recently, we rolled out a new version of our plugin(7.15.0). Could you please try to use it and let me know about the result? It should work with Cordova 8+ for both platforms 

https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/releases/tag/7.15.0

**Comment by wfhm** [comment]
@guirip any news?

**Comment by guirip** [comment]
Hey
I am sorry you have not received feedback on this one. I am not working for
this company now but I transferred them your message as soon as I got your
notification. It seems like no news is good news...
All the best
Cheers

**Comment by wfhm** [comment]
@guirip Thank you for the update!
