### ISSUE TITLE
Notifications showed with icon and App Title 

### ISSUE THREAD

**Issue by HamedOv** [Pushwoosh/pushwoosh-phonegap-plugin#314]
Hi, I've a problem with phonegap build plugin, notifications just showed up with app icon and app title, no header, no message ..., even I can't get the message using event.notification.message in the push-notification event. it's always empty.

I'm using latest version of PhoneGap build, lastest version of PushWoosh plugin, Android 9.
here is the related config part:
![image](https://user-images.githubusercontent.com/39281068/57184515-bd9e5000-6ed1-11e9-888a-f3e42fcf2aa9.png)

**Comment by HamedOv** [comment]
<preference name="android-build-tool" value="gradle" />
<gap:plugin name="pushwoosh-pgb-plugin" source="npm" version="7.0.6" />
<plugin name="cordova-plugin-whitelist" source="npm" />
  <allow-navigation href="*" />
  <access origin="*" />
  <access origin="*.pushwoosh.com" />
  
<platform name="android">
    <resource-file src="google-services.json" target="app/google-services.json" />
</platform>

**Comment by wfhm** [comment]
Hello @HamedOv 

I have just tried it with a fresh project and it worked just fine for me. May I ask you to share a reproducer with us so we could check it on our side? You can send it to help@pushwoosh.com with a reference to this issue.

**Comment by wfhm** [comment]
@HamedOv did you have a chance to communicate with the support team?
