### ISSUE TITLE
pushwoosh-cordova-plugin permissions

### ISSUE THREAD

**Issue by gtsopour** [Pushwoosh/pushwoosh-phonegap-plugin#317]
Going from the com.pushwoosh.plugins.pushwoosh to the latest pushwoosh-cordova-plugin it seems that several new permissions appeared. This will block most probably the Android auto-update for thousand of my users. Is there any suggestion around this topic? Can I remove them somehow?  
  
 @wfhm Do you have any suggestion?
<uses-permission android:name="com.amazon.device.messaging.permission.RECEIVE" /> 
    <permission
        android:name="com.lg.lglearningcanada.permission.RECEIVE_ADM_MESSAGE"
        android:protectionLevel="signature" />

    <uses-permission android:name="com.lg.lglearningcanada.permission.RECEIVE_ADM_MESSAGE" /> 
    <uses-permission android:name="com.sec.android.provider.badge.permission.READ" />
    <uses-permission android:name="com.sec.android.provider.badge.permission.WRITE" /> 
    <uses-permission android:name="com.htc.launcher.permission.READ_SETTINGS" />
    <uses-permission android:name="com.htc.launcher.permission.UPDATE_SHORTCUT" /> 
    <uses-permission android:name="com.sonyericsson.home.permission.BROADCAST_BADGE" />
    <uses-permission android:name="com.sonymobile.home.permission.PROVIDER_INSERT_BADGE" /> 
    <uses-permission android:name="com.anddoes.launcher.permission.UPDATE_COUNT" /> 
    <uses-permission android:name="com.majeur.launcher.permission.UPDATE_BADGE" /> 
    <uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BADGE" />
    <uses-permission android:name="com.huawei.android.launcher.permission.READ_SETTINGS" />
    <uses-permission android:name="com.huawei.android.launcher.permission.WRITE_SETTINGS" /> 
    <uses-permission android:name="android.permission.READ_APP_BADGE" /> 
    <uses-permission android:name="com.oppo.launcher.permission.READ_SETTINGS" />
    <uses-permission android:name="com.oppo.launcher.permission.WRITE_SETTINGS" /> 
    <uses-permission android:name="me.everything.badger.permission.BADGE_COUNT_READ" />
    <uses-permission android:name="me.everything.badger.permission.BADGE_COUNT_WRITE" /> 
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" /> 
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" /> 
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />

**Comment by wfhm** [comment]
Hi @gtsopour,

No, you are not able to remove these permissions somehow, since such changes will critically affect the operation of our SDK.

**Comment by gtsopour** [comment]
@wfhm Thanks for the quick response. I really appreciate that. Do you know if these permissions will affect the auto-update functionality? Because I see that there are critical and non-critical permissions.

**Comment by wfhm** [comment]
@gtsopour,

Judging by the information from the threads below, it seems that every new permission will affect the auto-update functionality.

​ ![](https://pushwoosh.zendesk.com/attachments/token/QnbmOlUG9pZjvG22YljmDYKH4/?name=Screenshot+2019-06-17+at+15.43.44.png)
https://support.google.com/googleplay/answer/6014972

https://android.stackexchange.com/questions/2958/why-do-some-of-my-apps-show-update-and-some-show-update-manual
