### ISSUE TITLE
Notification icon doesn't change color on Android 6.0

### ISSUE THREAD

**Issue by lingros13** [Pushwoosh/pushwoosh-phonegap-plugin#319]
Hello,

I have custom icon in res/drawable/pw_notification.png and it works, but on some Android devices the icon doesn't change color according to background color, so when the background is light, the icon isn't visible (my icon is the house next to a clock):
![light_background](https://user-images.githubusercontent.com/53258396/61787136-b1ee6580-adfe-11e9-8977-39584cae9ece.png)

The problem is specifically on Huawei Redmi 3S with Android 6.0.1. I've tested on another Android with 6.0 (some Prestigio phone) and it works fine, it works on Samsung S4 with Android 7 (custom ROM) as well.

I suspect there is a problem with MIUI firmware. Or is the icon bad?
My pw_notification.png is there:
![pw_notification](https://user-images.githubusercontent.com/53258396/61787293-0691e080-adff-11e9-9052-67ec7dbbfa1f.png)

**Comment by wfhm** [comment]
Hi @lingros13,

Yes, it seems that this behaviour is caused by the MIUI firmware since on other devices this functionality works correctly. I can say that unfortunately similar issues and bugs are quite common for custom launchers from Chinese OEMs. Please note that the manufacturer's custom launcher is beyond Pushwoosh SDK control.

**Comment by lingros13** [comment]
But applications not build with cordova (or maybe not using PushWoosh) don't have this issue - you can see e. g. Zoiper in the screenshot above (the icon next to mine) - its icon is fine.

**Comment by wfhm** [comment]
@lingros13,

Could you please specify the resolution of the icon you are using for notifications(res/drawable/)?

**Comment by lingros13** [comment]
The resolution is 96 x 96 px, is it bad? I've attached the icon to my first post.
