### ISSUE TITLE
Zip Path Traversal Vulnerability

### ISSUE THREAD

**Issue by ipehimanshu** [Pushwoosh/pushwoosh-phonegap-plugin#320]
Security alert

Your app contains an unsafe unzipping pattern that may lead to a Path Traversal vulnerability. Please see this Google Help Center article to learn how to fix the issue.

Vulnerable locations:

com.pushwoosh.internal.utils.e.a

**Comment by wfhm** [comment]
Hi @ipehimanshu,

Please note that this issue is already fixed with the version 7.14.0 of our plugin. Please update the version of the Pushwoosh plugin in your app to the latest one in order to fix this warning(7.17.1).

https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/releases/tag/7.17.1
