### ISSUE TITLE
framework not found StoreKit causing Cordova build to fail

### ISSUE THREAD

**Issue by jfbloom22** [Pushwoosh/pushwoosh-phonegap-plugin#324]
Cordova 9.0
Cordova iOS platform: 5.0.1
pushwoosh-phonegap-plguin 7.18.2, 7.18.1, 7.18.0, 7.17.1, 7.13.0
Xcode 11.0

After I add the pushwoosh-phonegap-plugin `Cordova build iOS` start failing with the following error:

```
ld: framework not found Storekit
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jfbloom22** [comment]
I don't understand what the issue is, but I was able to fix it.  I noticed the StoreKit framework looked different from the Security framework:  https://www.dropbox.com/s/bt4cweq2vl5yrss/Screenshot%202019-10-05%2011.49.52.png?dl=0
see how it is a white cube rather than the briefcase icon?

I removed StoreKit and added it again.  Now it looks the same as the Security framework and my project builds successfully.  https://www.dropbox.com/s/cmwoelz2q0gpgcm/Screenshot%202019-10-05%2011.50.12.png?dl=0

I'll leave this open for a couple days to see if anyone can shed some light on the situation.  Any ideas?

**Comment by wfhm** [comment]
@jfbloom22,

Just tried to reproduce it on a sample project with the same versions of Cordova, XCode and the plugin - everything works fine on our side. It looks like in some cases Cordova generates XCode project incorrectly, or, probably, it is caused by third-party plugins.
