### ISSUE TITLE
Need better error message for invalid google id

### ISSUE THREAD

**Issue by pburrows** [Pushwoosh/pushwoosh-phonegap-plugin#337]
Only by running logcat for pushwoosh was I able to determine that I had entered the wrong projectid for google. In logcat I saw this message:

    Pushwoosh: [RegistrarWorker] FCM registration error:INVALID_SENDER

That error message should get bubbled up to the error handler for the `registerDevice` method call so that we can see this error in the console.

**Comment by wfhm** [comment]
@pburrows,

Added it to our backlog, I will let you know once there is any ETA on it.

**Comment by wfhm** [comment]
Done in 6.1.4.
