### ISSUE TITLE
module pushwoosh-cordova-plugin.PushNotification not found

### ISSUE THREAD

**Issue by David-moonsite** [Pushwoosh/pushwoosh-phonegap-plugin#344]
i get this error : 
module pushwoosh-cordova-plugin.PushNotification not found

I'm run on IOS native device . 

in my code i use it like this :
`   pushNotification = cordova.require("pushwoosh-cordova-plugin.PushNotification"); 
`

**Comment by wfhm** [comment]
@David-moonsite I apologize for the delayed response! I have tried reproducing the issue, and it works just fine on my end. Can you please let me know if you can reproduce the issue with [our sample app](https://github.com/Pushwoosh/pushwoosh-phonegap-cordova-sample) and, if yes, provide the steps to do it?
