### ISSUE TITLE
push notification not comes into android cordova android 8.1.0 

### ISSUE THREAD

**Issue by ipehimanshu** [Pushwoosh/pushwoosh-phonegap-plugin#348]
Hello sir

We are not received push notification with latest plugin version

here is our info

Ionic CLI                     : 6.12.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 9.0.6
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0
Cordova:
   Cordova CLI       : 10.0.0
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 20 other plugins)
Utility:
   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 0.2.8
System:
   ios-deploy : 1.11.0
   ios-sim    : 8.0.2
   NodeJS     : v14.16.1 (/usr/local/bin/node)
   npm        : 6.14.12
   OS         : macOS Big Sur
   Xcode      : Xcode 12.0.1 Build version 12A7300
   
   and pushwoosh-cordova-plugin@8.1.1 
   
   Ios device received push perfect but android device not working. no push comes, so can you please help us?
   
   Thanks

**Comment by ipehimanshu** [comment]
@wfhm sir any update for this issue please ?

**Comment by ipehimanshu** [comment]
i have tested with cordova android 9.0.0 but it not received push. and one most important thing is i have checked with our live client app which we just published some day ago and those apps also not received any push for android, so it is very critical issue so far for us, 
So please help us to resolve issue
Thanks

**Comment by wfhm** [comment]
@ipehimanshu Can you share a bit more detail on the issue? Do you get any errors in the Message History or in device console logs? Also, resolving this issue might require you to provide sensitive data, such as your account name, App ID etc., so I suggest submitting a support ticket at https://help.pushwoosh.com/hc/en-us/requests/new.

**Comment by ipehimanshu** [comment]
ok it solved.
