### ISSUE TITLE
In-app notification on iOS when application is active

### ISSUE THREAD

**Issue by justinpatten** [Pushwoosh/pushwoosh-phonegap-plugin#35]
Per everything that I have read, we should not be receiving an in-app pop up when a push message is received and the app is open. However, we are. The message pops up, which has a native look/feel, and has OK/Cancel buttons. 
We do not have anything in the JavaScript code to alert when a push is received.

**Comment by calendee** [comment]
Can someone proive details on this info.plist suggestion.  I have no such file.  Suddenly out of the blue I am also getting the notification in the app when active.

Xcode shows : "Will show push notifications alert"
