### ISSUE TITLE
Invalid config-file tag in plugins.xml file

### ISSUE THREAD

**Issue by Benvanderlinden** [Pushwoosh/pushwoosh-phonegap-plugin#353]
Hi,

In the plugins.xml file there is a invalid <config-file> tag.

https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/blob/outsystems/plugin.xml

**Invalid tag:**

`_<config-file>
		<access origin="*.pushwoosh.com" />
</config-file>_`

This tag is preventing us to use the latest MABS version for our Outsystems mobile app build.
Can someone please remove this invalid tag and create a new version?
Thanks

Ben

PS comment from Outsystems support:

We were able to identify the root cause in an offending configuration.  The problem lies in the Pushwoosh plugin.  Its plugin.xml contains an invalid <config-file> tag.  It lacks both the target and parent attributes:

<config-file>
  <access origin="*.pushwoosh.com" />
</config-file>

Analyzing Pushwoosh's master branch (https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/blob/master/plugin.xml), such invalid <config-file> tag is no longer present in the plugin.xml file, as opposed to the OutSystems branch (https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/blob/outsystems/plugin.xml) you are using.  Further checks show that this was already fixed by Pushwoosh in this Github commit [1] and release [2].

**Comment by wfhm** [comment]
@Benvanderlinden, Thanks for pointing this out! We will update the Outsystems branch in the nearest future.

**Comment by wfhm** [comment]
@Benvanderlinden should be fixed now.
