### ISSUE TITLE
Android compilation failure (PW 8.3.2)

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-plugin#367]
8.3.1 is good as usual but your latest version gives:

> Task :app:compileArm64ReleaseJavaWithJavac FAILED
/Users/foo/bar/platforms/android/app/src/main/java/com/pushwoosh/plugin/pushnotifications/PushNotifications.java:171: error: missing return statement
        }
        ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

**Environment**:
cordova@11.0.0

**Comment by wfhm** [comment]
@zarko-tg Thanks for reporting this. Fixed in 8.3.3.
