### ISSUE TITLE
8.3.5 Unable to build for iOS

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-plugin#371]
...
/Users/foo/app/platforms/ios/AppName/Plugins/pushwoosh-cordova-plugin/ios/PushNotification.m:14:9: fatal error:
      'PWLog.h' file not found
#import "PWLog.h"
        ^~~~~~~~~
1 error generated.

---
Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 14 other plugins)

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v12.22.12
   npm               : 6.14.16
   OS                : macOS Monterey
   Xcode             : Xcode 13.4.1 Build version 13F100

**Comment by wfhm** [comment]
Thanks @zarko-tg, will be fixed shortly.

**Comment by wfhm** [comment]
Fixed in 8.3.6.
