### ISSUE TITLE
8.3.6 Unable to build for Android

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-plugin#374]
...
> Task :app:compileArm64ReleaseJavaWithJavac FAILED
/Users/foo/app/platforms/android/app/src/main/java/com/pushwoosh/plugin/pushnotifications/PushNotifications.java:182: error: cannot find symbol
                                        if (result.isSuccess() && result.getData != null) {
                                                                        ^
  symbol:   variable getData
  location: variable result of type Result<RegisterForPushNotificationsResultData,RegisterForPushNotificationsException>
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileArm64ReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

Cordova:

Cordova CLI : 11.0.0
Cordova Platforms : ios 6.2.0
Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 14 other plugins)

System:

Android SDK Tools : 26.1.1
NodeJS : v12.22.12
npm : 6.14.16
OS : macOS Monterey
Xcode : Xcode 13.4.1 Build version 13F100

**Comment by wfhm** [comment]
@zarko-tg fixed in 8.3.7. Please let me know if the issue persists.
