### ISSUE TITLE
iOS Build failed on 8.3.6 There is no XCFramework found

### ISSUE THREAD

**Issue by EthanCG** [Pushwoosh/pushwoosh-phonegap-plugin#375]
Hi

I get error error: There is no XCFramework found at '/platforms/ios/Pods/PushwooshXCFramework/XCFramework/Pushwoosh.xcframework'. (in target 'App' from project 'App')

ionic cli : 6.20.1
Ionic Framework               :              @ionic/angular 5.9.4
@angular-devkit/build-angular :      14.2.1
@angular-devkit/schematics    :      14.2.1
@angular/cli                  :                   10.0.8
@ionic/angular-toolkit        :             7.0.0
 Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : android 10.1.2, ios 6.2.0
ios-deploy        : 1.11.4
   ios-sim           : 8.0.2
   NodeJS            : v16.13.1 (/Users/henrique/.nvm/versions/node/v16.13.1/bin/node)
   npm               : 8.19.1
   OS                : macOS Monterey
   Xcode             : Xcode 13.4.1 Build version 13F100

**Comment by wfhm** [comment]
@EthanCG hi,

I was unable to reproduce the issue locally, so could you please share the steps to reproduce it?

**Comment by VaishaliFoko10** [comment]
Hi @wfhm, I am facing the same issue. The app was working fine with earlier version for plugin but when I did an update it gives me the same error that EthanCG shared

**Comment by VaishaliFoko10** [comment]
> Hi @wfhm, I am facing the same issue. The app was working fine with earlier version for plugin but when I did an update it gives me the same error that EthanCG shared

issue is resolved for me when I did `sudo gem install cocoapods :)

**Comment by wfhm** [comment]
@EthanCG any updates on the issue?
