### ISSUE TITLE
Binary files not allowed in bundle

### ISSUE THREAD

**Issue by VaishaliFoko10** [Pushwoosh/pushwoosh-phonegap-plugin#378]
Latest Version - The plugin works fine but when we create an archive for iOS and try to upload it to the app store. The app store complains that binary files are not allowed in the package

**Comment by wfhm** [comment]
Checking it.

**Comment by zarko-tg** [comment]
Likewise. This is blocking new releases to AppStore. We're likely reverting to one or another older version that works for both iOS and Android.

Screenshot from Transporter / Xcode 14:
<img width="787" alt="Screenshot 2022-09-26 at 21 56 08" src="https://user-images.githubusercontent.com/6142411/192368670-1c951445-974b-45c9-ac3e-36b12935dd64.png">

https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle

**Comment by wfhm** [comment]
@zarko-tg  @VaishaliFoko10 what Cordova and cordova-ios versions do you use in your project? Also @VaishaliFoko10 do you use Xcode 14 as well?

For now, it looks like Apple changed something in Xcode 14 (or maybe something was changed with the latest cordova-ios version), and now libraries are being linked to the bundle. Removing the directory from **Copy Bundle Resources** solved the issue for me. Could you please try the same and let me know about the results?
<img width="673" alt="Screenshot 2022-09-27 at 11 57 19" src="https://user-images.githubusercontent.com/13344781/192554035-3acdd365-1f39-40b8-9667-f57057a2c503.png">

**Comment by VaishaliFoko10** [comment]
Cordova: 11
 Cordova-ios versions: 6.2
using Xcode 13.1
Thanks @wfhm, I will try this and let you know

**Comment by wfhm** [comment]
Fixed in 8.3.8
