### ISSUE TITLE
Issue with latest version of Phonegap

### ISSUE THREAD

**Issue by damok77** [Pushwoosh/pushwoosh-phonegap-plugin#38]
I've had a working version of the pushwoosh plugin until I just updated it.

I'm using 3.5.0-0.20.10 of Phonegap and the latest version of the pushwoosh plugin from Github. 
No I get the following during the initialization.

~07-31 21:10:26.131: W/System.err(1443): org.json.JSONException: Index 0 out of range [0..0)
07-31 21:10:26.131: W/System.err(1443):     at org.json.JSONArray.get(JSONArray.java:263)
07-31 21:10:26.135: W/System.err(1443):     at org.json.JSONArray.getJSONObject(JSONArray.java:480)
07-31 21:10:26.135: W/System.err(1443):     at com.pushwoosh.plugin.pushnotifications.PushNotifications.initialize(PushNotifications.java:151)
07-31 21:10:26.135: W/System.err(1443):     at com.pushwoosh.plugin.pushnotifications.PushNotifications.execute(PushNotifications.java:361)
07-31 21:10:26.139: W/System.err(1443):     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:65)
07-31 21:10:26.139: W/System.err(1443):     at org.apache.cordova.PluginManager.execHelper(PluginManager.java:242)
07-31 21:10:26.143: W/System.err(1443):     at org.apache.cordova.PluginManager.exec(PluginManager.java:227)
07-31 21:10:26.143: W/System.err(1443):     at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:53)
07-31 21:10:26.147: W/System.err(1443):     at org.apache.cordova.CordovaChromeClient.onJsPrompt(CordovaChromeClient.java:227)
07-31 21:10:26.147: W/System.err(1443):     at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:655)
07-31 21:10:26.147: W/System.err(1443):     at android.os.Handler.dispatchMessage(Handler.java:99)
07-31 21:10:26.151: W/System.err(1443):     at android.os.Looper.loop(Looper.java:137)
07-31 21:10:26.151: W/System.err(1443):     at android.app.ActivityThread.main(ActivityThread.java:4745)
07-31 21:10:26.155: W/System.err(1443):     at java.lang.reflect.Method.invokeNative(Native Method)
07-31 21:10:26.155: W/System.err(1443):     at java.lang.reflect.Method.invoke(Method.java:511)
07-31 21:10:26.155: W/System.err(1443):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
07-31 21:10:26.159: W/System.err(1443):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
07-31 21:10:26.159: W/System.err(1443):     at dalvik.system.NativeStart.main(Native Method)
07-31 21:10:26.163: D/PushNotifications(1443): Plugin Called
07-31 21:10:26.167: W/System.err(1443): java.lang.NullPointerException
07-31 21:10:26.167: W/System.err(1443):     at com.pushwoosh.plugin.pushnotifications.PushNotifications.internalRegister(PushNotifications.java:183)
07-31 21:10:26.170: W/System.err(1443):     at com.pushwoosh.plugin.pushnotifications.PushNotifications.execute(PushNotifications.java:368)
07-31 21:10:26.170: W/System.err(1443):     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:65)
07-31 21:10:26.174: W/System.err(1443):     at org.apache.cordova.PluginManager.execHelper(PluginManager.java:242)
07-31 21:10:26.174: W/System.err(1443):     at org.apache.cordova.PluginManager.exec(PluginManager.java:227)
07-31 21:10:26.174: W/System.err(1443):     at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:53)
07-31 21:10:26.178: W/System.err(1443):     at org.apache.cordova.CordovaChromeClient.onJsPrompt(CordovaChromeClient.java:227)
07-31 21:10:26.178: W/System.err(1443):     at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:655)
07-31 21:10:26.178: W/System.err(1443):     at android.os.Handler.dispatchMessage(Handler.java:99)
07-31 21:10:26.182: W/System.err(1443):     at android.os.Looper.loop(Looper.java:137)
07-31 21:10:26.182: W/System.err(1443):     at android.app.ActivityThread.main(ActivityThread.java:4745)
07-31 21:10:26.186: W/System.err(1443):     at java.lang.reflect.Method.invokeNative(Native Method)
07-31 21:10:26.190: W/System.err(1443):     at java.lang.reflect.Method.invoke(Method.java:511)
07-31 21:10:26.190: W/System.err(1443):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
07-31 21:10:26.190: W/System.err(1443):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
07-31 21:10:26.194: W/System.err(1443):     at dalvik.system.NativeStart.main(Native Method)

please please help ,  if I do not get a solution I will have to use something else

**Comment by Pmagz** [comment]
Hi Damok, im having this issue, kindly elaborate your solution

**Comment by shaders** [comment]
If you have this error make sure you follow the guide correctly. Some parameters from registerDevice function has been moved to onDeviceReady function.

**Comment by Pmagz** [comment]
Thank you Shader,

It worked.
