### ISSUE TITLE
'Pushwoosh/Pushwoosh.h' file not found

### ISSUE THREAD

**Issue by jwasnoggin** [Pushwoosh/pushwoosh-phonegap-plugin#387]
I'm trying to use this plugin with an Ionic Cordova project, but the build for iOS fails with the message "'Pushwoosh/Pushwoosh.h' file not found". 

I can see that this file exists inside the Pods folder, but it appears the plugin code can't find it.

How can I fix this problem?

**Comment by jwasnoggin** [comment]
I was able to build for iOS by downgrading to version 8.3.4. However, this breaks the Android build due to https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/376.

**Comment by jwasnoggin** [comment]
I think it may have been due to an error while adding the platform. The above commands resulted in a different error but didn't fix the problem. However removing and reinstalling the iOS platform solved the problem.

**Comment by ipehimanshu** [comment]
@jwasnoggin 

which cordova ios version it works for you sir?


Thank you

**Comment by jameswassink** [comment]
This is with cordova 10 and cordova-ios 5.1.1

**Comment by jwasnoggin** [comment]
@ipehimanshu This is with cordova 10 and cordova-ios 5.1.1
