### ISSUE TITLE
'Pushwoosh/Pushwoosh.h' file not found cordova ios 6.2.0 and pushwoosh plugin 8.3.13

### ISSUE THREAD

**Issue by ipehimanshu** [Pushwoosh/pushwoosh-phonegap-plugin#388]
Hello 

we are using ionic angular with cordova ios 6.2.0

here is ionic info

Ionic:

   Ionic CLI          : 6.20.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.10
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 16 other plugins)

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.2) : 1.7.1

System:

   Android SDK Tools : 26.1.1 (/Users/herobarua/Library/Android/sdk)
   ios-deploy        : 1.12.1
   ios-sim           : 8.0.2
   NodeJS            : v14.20.0 (/usr/local/bin/node)
   npm               : 6.14.17
   OS                : macOS
   Xcode             : Xcode 14.2 Build version 14C18
   
   and here is plugin list used
   
   cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 3.0.0 "cordova-plugin-androidx"
cordova-plugin-appinfo 2.1.2 "AppInfo Plugin"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-keychain-touch-id 3.3.0 "TouchID and Keychain"
cordova-plugin-network-information 3.0.1-dev "Network Information"
cordova-plugin-splashscreen 6.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.5 "Whitelist"
pushwoosh-cordova-plugin 8.3.13 "Pushwoosh"

we got error while build like

![image](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/assets/26652038/218cf541-a584-47c6-9ea0-4881c7d47b7c)

so can you please help us

Thank you

**Comment by Techsorcist** [comment]
@ipehimanshu, may I ask you if your project contains the `.xcworkspace` file that is generated after adding the plugin, and you open it?

Could you navigate to the iOS project directory and run 2 commands via the terminal:
```
1. pod deintegrate
2. pod install
```

_In case you still got an error, remove and re-install the iOS platform — that should solve the issue._

**Comment by ipehimanshu** [comment]
ok

if we open  xcworkspace then it works for us,

thank you
