### ISSUE TITLE
[Bug]: Capacitor 6 can't get notification on android

### ISSUE THREAD

**Issue by GiannisS** [Pushwoosh/pushwoosh-phonegap-plugin#410]
### Documentation

- [x] I've checked the guide, but it doesn't help me to resolve the issue.

### Description

I am using capacitor 6 and it seems that I can't receive notifications. The device seem to register correctly, I do get an HWID and a pushToken but whenever I try to send a test push notification, although it seems that it got sent, I never receive it on my android nor on the in-app listener.

### Bug severity

Low

### Steps to Reproduce

Just run it on Capacitor 6

### Your Pushwoosh Cordova plugin version

8.3.28

### cordova package version

cordovaAndroidVersion = '10.1.1'

### Affected platforms

- [X] Android
- [ ] iOS

### Affected OS versions and/or devices

Android 12

**Comment by enginseer-dev** [comment]
Hello, @GiannisS 

We want to test your application on our devices.

Can you please send us the link to the APK at help@pushwoosh.com?

**Comment by enginseer-dev** [comment]
Hello, @GiannisS 

Since we've resolved your issue via email, I am now closing this GitHub issue.

Feel free to message us, if you have any questions.
