### ISSUE TITLE
Command failed with exit code 65

### ISSUE THREAD

**Issue by mcbejn** [Pushwoosh/pushwoosh-phonegap-plugin#46]
Hi everyone,

I have successfully installed the cordova plugin for Android, and a couple of days ago in the same project for iOS as well. I removed it temporarily from the iOS app, and today tried to install again but this time without any success. Below is the error I get when I run cordova build ios. I am using the latest Ionic framework (Cordova CLI) to install the plugin.
I see that there have been some edits 2 days ago, is it possible that some bug was introduced now?
Big thanks for any help, it's a pretty urgent matter :)

The following build commands failed:
    Ld build/emulator/MyApp.app/MyApp normal i386
(1 failure)
Error: /Users/xxxx/platforms/ios/cordova/build: Command failed with exit code 65

at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

**Comment by Wang0620** [comment]
I am also getting the same issue. Here are error log.
The following build commands failed:
	Ld build/emulator/herb.app/herb normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,.....

**Comment by shaders** [comment]
fixed

**Comment by Wang0620** [comment]
Thank you very much, Shader. :) I've just tried. It works now. You are very helpful.
