### ISSUE TITLE
window.history.back() does not work after pushwoosh opens my app

### ISSUE THREAD

**Issue by iwantwin** [Pushwoosh/pushwoosh-phonegap-plugin#99]
I implemented pushwoosh in a succesfull manner for multiple phonegap apps in the past. I recently discovered that my app wil stop working when it is opened by pushwoosh.

In a normal situation, pushes will be received and handled (in my case, a popup will be shown). Pushwoosh initialization and device registration happens as expected. When my app is paused (send to background), clicking a pushwoosh push notification will bring the app to the foreground as expected. When I close my app (remove it from recent apps), clicking a pushwoosh push notification will open te app and the push will show up.

The expected situation though, is that we will be able to navigate back and forth in my application. I do this by using the hashparameters of my app's url. This works perfect in a normal way, and also in the pause-resume way. When my app was closed and opened, only the forward navigation works! 

Forward navigation is handled by the "hashchange" eventhandler. Backward navigation is triggered by using window.history.back();. This last call does not work when it is bound to the backbutton eventhandler, does not work from console and also not from a clickhandler. The assumption is that window.history.back does not work at all, but maybe the entire window.history is not working, I could not test window.history.forward, because obviously, forward is not supported if you can't go back. window.history.go(-1); is not working either though.The window.history does show a length property that consists of the amount of pages that should be visited.

I'm not seeing anything in the source code that could cause this, but I was thinking maybe it had tot do something with the "message" intent or something. Can you please help me figure out what is going on? This situation only occurs when my app gets started by a push-notification, not just in my current project but also in older projects where I used pushwoosh!

**Comment by shaders** [comment]
Could you send any simple sample app to reproduce the behavior?

**Comment by pixelgroup-israel** [comment]
@iwantwin have you solved it out? I am facing exactly the same issue here

**Comment by iwantwin** [comment]
@pixelgroup-israel it's a long time ago! I remember trying to make a simple sample app, and while I was removing stuff that was seemingly irrelevant I found some code that was causing the issue. I no longer have access to the code base since I switched jobs.
